### ISSUE TITLE
Can't inject new activities in postActivity middleware

### ISSUE THREAD

**Issue by codefoster** [Microsoft/botbuilder-js#109]
I'm trying to create middleware that injects activities into the list of activities the middleware receives. I am facing two issues:

1. I receive the list of activities as `context.responses` as well as `activities` and am confused regarding which to use.

1. Regardless of whether I choose `context.responses` or `activities`, if I manipulate the array it has no effect on what's sent to the adapter. I am copying an existing activity in order to create new ones in order to maintain the conversation identifier. Instead, the bot merely response with the original list of activities.

**Comment by billba** [comment]
My proposal for fixing this is not to have `postActivity` mutate `activities`, but instead pass a new `activities` array to `next()`, e.g.

```ts
const toUpperMiddleware = {
    postActivity(context, activities, next) {
        return next(activities.map(activity => activity.type === 'message'
            ? { ... activity, text: activity.text.toUpper() }
            : activity
        );
    }
}
```

**Comment by codefoster** [comment]
If there's no other reason to have a separate `activities` parameter passed in to the `postActivity` function, then I would recommend it be eliminated to avoid confusion. It's not difficult to discover the responses array in `context.responses`.

**Comment by Stevenic** [comment]
So in the `M1 bits` you should manipulate the passed in `activities` array. I'm not completely sure why the adapter is ignoring your additions.  The reason you don't want to manipulate the `responses` array directly is that the activities array is a snapshot of the responses array and new responses could be getting pushed onto it while the current batch is being flushed.

All of this has changed in the `M2 bits` and the batching pieces have been removed so there is no `responses` array anymore (at least not by default.) In M2 you HAVE to manipulate the `activities` but that should definitely work.

**Comment by Stevenic** [comment]
@billba that's actually where I started at with M2 (passing a new activity array) but others on the team didn't like it and since it meant a different signature for `next()` then anything else I went ahead and left the "manipulate the array" approach in place.

**Comment by Stevenic** [comment]
I would definitely love for you both to start playing with my "m2" branch sometime soon.  Everything builds and the [echobot](https://github.com/Microsoft/botbuilder-js/tree/m2/samples/echobot-ts) and [alarmbot](https://github.com/Microsoft/botbuilder-js/tree/m2/samples/alarmbot-ts) samples have been updated.  You could also look at the dialogs version of [alarmbot](https://github.com/Microsoft/botbuilder-js/blob/m2/samples/dialogs/alarmbot-ts/src/app.ts) if you wanted to see the use of my `BatchOutput` middleware which adds back in the batch based semantics for sending replies.

**Comment by billba** [comment]
For what it's worth, until ten minutes ago I didn't know about the JS `array.splice()` operator, so I didn't realize you could fully modify an array in-place. But the JS community is moving towards immutable operations, and now every time I mutate data it makes me feel dirty. I hear the valid concern about a different signature for `next()` but this pipe is already a little different because it's the only one where you have to return the result of `next()` so I think it can go ahead and be a little more different. After all, you'll find out right away if it doesn't work :-)

**Comment by Stevenic** [comment]
@cleemullins is currently working on the c# version of my "m2" branch and good or bad we're just trying to get things aligned so that as we do DCR's like this we can make them to both SDKs as appropriate. The c# SDK currently works the same way so I'd suggest either adding a DCR in the C# repo for this or just adding this to your list of discussion points. 

I'm mainly suggesting the C# repo for DCR's because the community is a bit more active over there and we'll get more opinions voiced.

**Comment by billba** [comment]
Agreed on alignment. My problem is that I'm not really a C# guy so I can't really speak authoritatively about implementation, community, etc.

**Comment by billba** [comment]
(It's probably a little onerous to insist that anyone posting an issue to this repo also have to post one to the .net repo in order to make something happen.)

**Comment by Stevenic** [comment]
I'm not either but I'm muddling through. The only saving grace is the SDK's are largely the same so while I'm not exactly sure what a C# developer would expect I can at least weigh in on the intent of the SDK's.

**Comment by Stevenic** [comment]
I only tell microsofties that @billba  :) In all seriousness we're working towards having a single GitHub project that we can use to collate issues and DCR's like this across all of the repo's but I was just suggesting the other repo because more people will see it.  I think you could just cross-link back over to hear so that others on the C# side of things know its here.

**Comment by Stevenic** [comment]
Closing this as the bug should be fixed. Opened a new issue to track the discussion.
