### ISSUE TITLE
Define constants for Channel IDs

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-js#1100]
In dotnet we have centralized constants for channel ids [here](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Connector/Channels.cs). However, in Javascript there are channel id constants defined within the choice prompt classes, but they are used in nearby classes and I found occurrences of the string literals for channel ids.

We have new adapters for new channels coming and each one has a const for the channelId, it may be better to have this in BotBuilder.Connector to avoid future collisions but I'm not 100% sure. 

The alternative would be to have each new channel adapter expose a const with the channelId they handle so we don't have to modify the product when we add new channels, but we probably need to agree on where a dev would expect to find this definition so we are consistent across the board.

If we go with the alternative, devs would have two places for ChannelId (Connector and the adapter), which may be confusing I am more inclined to have it in a single place for consistency.

**Comment by stevengum** [comment]
As I mentioned internally, we should duplicate the constants in the connector and keep the current location in `botbuilder-dialogs`. We can't add a  `botframework-connector` dependency in `botbuilder-dialogs` because that would introduce Node.js dependencies in a browser-compatible library.

To maintain consistency between the two, we can add Azure DevOps Pipeline Task to verify that the `channelIds` are the same in the two files.

_P.S. I'm all for a single source of truth, but I don't think we can have a single source in this scenario._

**Comment by v-kydela** [comment]
The C# channel constants used to be in a nested class called `Channel.Channels` but then they were moved to just `Channels` (still in the same package). Perhaps it would be best to move them again to a more centralized shared location like the Bot Framework Schema package.

**Comment by stevengum** [comment]
If we move it to the schema package, it's accessible by all packages, even though the libraries used in the context of the browser should theoretically not need the channelIds. This works for me 👍

**Comment by stevengum** [comment]
New issue filed for this: #1354

We could add the constants to botbuilder-core....

**Comment by v-kydela** [comment]
@carlosscastro 
@stevengum 

Are there any plans to fix this?

**Comment by stevengum** [comment]
This is not tied to any milestone currently so it hasn't been up for discussion. I'm going to assign it to R8 for now to get it into triaging discussion.
