### ISSUE TITLE
Suggestion: suggestedAction should be treated like choicePrompt in dialog/waterfall

### ISSUE THREAD

**Issue by v-ducvo** [Microsoft/botbuilder-js#117]
While testing the `MessageFactory.suggestedAction()`, I found that I cannot use it in a waterfall step because it does not cause the `dc.continue()` to continue executing my dialog. I suggest that it should.

For instance, this dialog cannot proceed to step 2 of the waterfall:

```JS
dialogs.add('suggestedAction', [
    async function(dc){
        var suggestedAction = MessageFactory.suggestedActions(["Red", "White", "Blue"], "What's your favorite color?");
        await dc.context.sendActivity(suggestedAction);
    },
    async function(dc, result){
        await dc.context.sendActivity("You choose: " + result.value);
        await dc.end();
    }
]);
```
However, this dialog will proceed to step 2 because it's using a prompt:

```JS
dialogs.add('suggestedAction', [
    async function(dc){
        await dc.prompt("choicePrompt", "What's your favorite color?", (["Red", "White", "Blue"]);
    },
    async function(dc, result){
        await dc.context.sendActivity("You choose: " + result.value);
        await dc.end();
    }
]);
```

Since the expected behavior of sending a "suggestedAction" is similar to a "choicePrompt" where both expect users to pick an option from the list of choices, it would make sense for the `dialogs.continue()` pass execution to the active dialog so it can process the user's input for a `suggestedAction` too.

**Comment by Stevenic** [comment]
So currently if you don't call `prompt()` or `begin()`  within a waterfall step and instead send an activity to the user without calling `end()` the waterfall will be automatically ended for you when the user replies.  This has always been "by design" and is almost always the result of a user simply forgetting to call `end()`.  You raise an interesting observation @v-ducvo that if I have more waterfall steps after the current one then my intention probably was NOT to end the dialog. I just didn't do the right thing to get the dialog to advance.

While it's not really practical for the waterfall to know that you sent `suggestedActions` so you really were trying to use a choice prompt, I think there is something smarter we can do here.  Instead of ending the dialog we could just pass the users response to the next step.  You're still going to have to be intentional about the code you're writing but it will let you now write a waterfall that moves forward without the use of prompts at all which I like.  So updating your example:

```JS
dialogs.add('suggestedAction', [
    async function(dc){
        var suggestedAction = MessageFactory.suggestedActions(["Red", "White", "Blue"], "What's your favorite color?");
        await dc.context.sendActivity(suggestedAction);
    },
    async function(dc, result){
        switch (result.toLowerCase()) {
             case 'red':
                  await dc.sendActivity(`I like Red too!`);
                  break;
              case 'white':
              case 'blue':
              default:
                  await dc.sendActivity(`Well my favorite is red.`);
                  break;
        }
        await dc.end();
    }
]);
```

The fact you always have to start a dialog to drive the waterfall forward has always felt a little heavy so I like that you can now write a waterfall without the use of prompts.  Open to feedback from others.

**Comment by Stevenic** [comment]
Waterfalls now follow the proposal I outlined above.

**Comment by Naveenbc** [comment]
The above shown code is not working for me. sendActivity is still ending my dialog
