### ISSUE TITLE
make Activity a discriminated type union

### ISSUE THREAD

**Issue by billba** [Microsoft/botbuilder-js#119]
Currently `Activity` is an interface of a million optional properties. Issues with this:
* TypeScript doesn't tell you which properties do or not apply to a given activity type. This means you could reference `context.request.text` for a `typing` activity, which is not valid.
* Because most properties are optional, in TypeScript's strict mode (which is now the default) you need to resort to the "non-null assertion operator" (e.g. `context.request.members!` for `conversationUpdate` activities)

The simple solution is to make `Activity` a discriminated type union.

A lot of this work has already been done over in [DirectLineJS](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L230). It would need to be updated with missing pieces.

**Comment by Stevenic** [comment]
It's the "missing pieces" part that's the core issue.  The core issue is our swagger file has it all in one big bucket and one of the key drivers to move to the use of swagger in v4 was so that the schema can always be auto generated. If we manually break these parts out to separate interfaces then we're back in the same boat of potentially getting out of sync with the service. This has been a nightmare in v3.

**Comment by Stevenic** [comment]
I should add that the issue is actually worse then this... We have no separation between input schema and output schema.  The fields that are valid on incoming activities are not the same for outgoing activities so it leaves us in a mode where we have to use `Partial<Activity>` for outgoing activities.  This means we get 0 type checking for outbound activities but the flip side owuld be that if we optomized for output you would have to wrap an `if(context.request.text)` around the input to prevent TS from complaining.

**Comment by billba** [comment]
> If we manually break these parts out to separate interfaces then we're back in the same boat of potentially getting out of sync with the service. This has been a nightmare in v3.

It sounds like you are saying that it would be a lot of work for Microsoft to create and update this manually, and I totally believe that. But consistent feedback is that it's really hard for developers to understand and work with `Activity`, which is the *core construct of the entire SDK*. So I think if it's humanly possible, which I'm confident it is, then the return on that investment across all SDK developers would be huge. 

> We have no separation between input schema and output schema

It may be that no one has formally defined this, but that is different than saying no separation is possible. `DirectLineJS` does in fact just codify the input schema, so it follows that it's possible to define the output schema.

Final question: doesn't `botbuilder-dotnet` do some version of this?

**Comment by Stevenic** [comment]
So this is all totally possible as I said we do it in the v3 SDK. It's been a nightmare to maintain as I said for numerous reasons that have little to do with the schema its self.  The biggest one is that when things change on the server side no one tells anyone or if they do tell someone the details of the change are locked up in some 100 message long email thread.  You would think that our schema would be fairly stable by now but it's not. We're literally making significant additions to the schema on a monthly basis. In fact if you've done this breakout already in direct line I'd be willing to bet you're out of alignment to some degree with the schema right now. You might say "well you need a process to stay in sync" and we have that. We auto generate everything off the Swagger.

I'm not actually disagreeing with you on the desire to have separate interfaces. But if we want this separation it needs to be part of our swagger.  We've had several meetings with @dandriscoll around this and it's currently not feasible.  There are [active discussion](https://github.com/Microsoft/botbuilder-dotnet/issues/282) on this topic on the `botbuilder-dotnet` side if you'd like to weigh in.

**Comment by sgellock** [comment]
Closed to to inactivity.
