### ISSUE TITLE
M2: Adapters are different than M1, .net

### ISSUE THREAD

**Issue by billba** [Microsoft/botbuilder-js#125]
Obviously adapters have changed form quite a bit since M1. Can you explain why the new approach is superior to the old one that many of us are used to?

In addition, wiring up a bot looks very different in botbuilder-js than in botbuilder-dotnet. These changes seem to exceed idiomatic differences.

We should agree on the best approach (M1 vs M2 vs Other) and then align the two SDKs as much as possible, modulo idiomatic differences.

**Comment by Stevenic** [comment]
I'll let @tomlm comment as well as he was the one that drove the adapter changes for M2. I'll try to enumerate the pros & cons with the M1 shape of adapters. First the pros:

- Adapters are simple in that they have a simple input & output mechanism for doing 2-way messaging with the user.
- Since adapters have know knowledge of the `Bot` class they'll be plugged into they can be easily used outside the scope of a class.
- You can write your Bot logic once and in most cases you can connect that bot to a different data source  with a single line code change.

Now the cons or I should probably call them issues because in some cases they were very real problems we were struggling with:

- Since the adapter has no knowledge of the bot or middleware stack it can't use any of the extensions points exposed by a bot.  Lets say you want to add your own custom logging function. We have you plug it in as a piece of middleware to the bot but since the adapter can't see what you plugged into the Bot it now needs its own concept of a plugable logger and you have to plug it into two places.  The M2 change doesn't completely solve this issue but the way we'll solve it seems clearer now and we will very clearly land on you plugging your new logger into one single spot.
- Like it or not, there are times when the adapter needs to pass more that just the activity to the bot.  The context is the perfect place to store these but the adapter has no knowledge of the context object and even if it did there's a big chicken and the egg problem around  who factories the context object.  To make this concrete MS Teams needs to not only add extensions to the base adapter to facilitate their multi-tenant related features but they also have a bunch of teams specific middleware they're building which needs access to the underlying credentials for the request.  We explored several different approaches of enhancing the M1 adapter to address these needs and they all sucked.  The M2 change completely solves this because it's the Teams adapter customize any part of the process they want.  They're now responsible for creating the BotContext object so they can add any extensions to the BotContext they want and they can just expose to the developer a new TeamsContext object.  And to echo that I had to do the exact same thing with the Alexa and Google Home adapters I built over the weekend.  Both Alexa & Google have their own way of working with state and I ended up having to extend the context object returned by those adapters to make that accessible to developers. It's not clear at all how I would expose this with the M1 version of adapters.

There are some other minor things like developers not understanding the relationship of the adapter to the bot or complaints about the fact we hide the internals of our Express/Restify middleware implementations too much. Bot those are minor in comparison to the very real issues above.

I agree that it sucks that we've kind of lost the one-line replace-ability of the current model but this is all boiler plate setup code anyway and the new adapter model solves real architectural problems for us.

**Comment by Stevenic** [comment]
Closing this specific issue as there are other issues discussing the topic of adapters. Please let me know if you think it should stay open. There's just be no further discussion.
