### ISSUE TITLE
M2: ConversationState/UserState are diffferent in JS/.net

### ISSUE THREAD

**Issue by billba** [microsoft/botbuilder-js#126]
Orthogonal to the correctness of the implementations, they are very different, seemingly exceeding the requirements of language differences. Notably, .net puts state accessors in `context`, which is very much against the spirit of "skinny Context".

We should agree on the best approach (JS M2 vs .net M2 vs Other) and then align the two SDKs as much as possible, modulo idiomatic differences.

**Comment by Stevenic** [comment]
Part of the issue here is that you could take the same basic spec/goal, give it to 5 different developers and you're going to get 5 similar but still different implementations. If I gave you my code for prompts and said port it to C# you're going to change things even if there's no real technical reason for you to do so. I made certain decisions when implementing my version of the M2 changes that reflect the way I think about the problem.  When Tom & Chris ported my changes to C# they kept things roughly the same but made changes that reflect the way they think about the problem. Does that mean their approach was any more right then mine? no. It's just different.  I personally think that the level of alignment being strived for here is close to impossible.  It's not sustainable. Even if we get thing perfectly align between the two languages (let alone 4) they will immediately start to diverge with the very next PR.  It's simply not achievable in a sustainable way.

**Comment by Stevenic** [comment]
The .NET and JS SDK's are out of alignment on this.

**Comment by Stevenic** [comment]
The latest memory system has much better alignment so closing this.
