### ISSUE TITLE
M2: ConversationState/UserState is conducive to namespace collisions

### ISSUE THREAD

**Issue by billba** [Microsoft/botbuilder-js#129]
Suppose I want to create a piece of middleware that maintains a variety of state for its own purpose.

In M1 I would have done:

```ts
class MW {
    constructor() {
    }

    receiveActivity(context, next) {
        context.state.conversation.count = context.state.conversation.count === undefined ? 0 : context.state.conversation.count;
        // use context.state.conversation.count for something
    }
}

...

bot.use(new MW());
```

... which would have relied on `context.state` having been set up by a previous piece of middleware.

In M1 this hidden dependency is removed, which means we now need/get to inject it in:

```ts
class MW = {
    const constructor(conversationState) {
        this.conversationState = conversationState;
    }

    onProcessRequest(context, next) {
        state = this.conversationState.get(context);
        state.conversation.count = state.conversation.count === undefined ? 0 : state.conversation.count;
        // use context.state.conversation.count for something
}

...

const conversationState = new ConversationState(new MemoryStorage());

bot.use(new MW(conversationState));
```

This works fine.

Now suppose that the bot logic also uses this same state property:

```ts
bot
    .use(new MW(conversationState))
    .processRequest(context => {
        // use context.state.conversation.count for something
    });
```

It could be that the intention is to share this state between my middleware and my bot logic, in which case it's working perfectly.

But let's say that is not the intention. If `MW` wants to maintain its own separate counter, it would have to do some namespacing, e.g.:

```ts
    onProcessRequest(context, next) {
        state = this.conversationState.get(context);
        state.conversation["github.com/billba/MW"].count = state.conversation["github.com/billba/MW"].count === undefined ? 0 : state.conversation["github.com/billba/MW"].count;
        // use state.conversation["github.com/billba/MW"].count for something
    }
```

This works in JaveScript, but creators of middleware will have to remember to do this.

Meanwhile, TypeScript users have to muck with typing to make this work, e.g.

```ts
interface MWState {
    ["github.com/billba/MW"]: {
        count: number;
    }
}

class MW = {
    conversationState: ConversationState<MWState>;

    constructor(conversationState: ConversationState<any>) {
        this.conversationState = conversationState;

    ...
}
```

This works, but any time you find yourself casting to or from `any` is a red flag. This one is letting us know that **there are multiple consumers of the same namespace**.

It would be much better if `ConversationState` had a concept of namespace built in, so that bot logic and multiple pieces of middleware could all be led to work with conversation state in a type-safe way, sharing when that is the intention, and in isolation when it is not.

**Comment by Stevenic** [comment]
So I'd like to break this into two parts; Cast Avoidance and Namespacing

### Cast Avoidance
I'm not sure how you can avoid having to cast from `<any>`.  At least not without adding complexity.  The C# guys already ran into this.

Lets simplify things and say your middleware definition is like this:

```JS
interface MWState {        
     count: number;
}

class MW = {
    constructor(private conversationState: ConversationState<MWState>) { }
}
```

You've just strongly typed your middleware constructor such that the bot now needs to know about your MWState interface and to avoid a compiler error it has to now derive its state from yours:

```JS
interface BotState extends MWState {
}
```

But the crappy part is that I may have to use multiple interface inheritance to keep everyone happy:

```JS
interface BotState extends MWState, MW2State, MW3State {
}
```

That would keep everyone in line from a TypeScript perspective but boy is it a PITA.  

###Namespacing
So regardless of the casting issues we could potentially add a formal concept of namespacing but why?  You're having to tell devs they should do something special in either case so there's an education component no matter what.  

They either have to know to call `this.conversationState = conversationState.asNamespace<MyState>('myPlugin')` or you just tell them they should call `const state: MyState = this.conversationState.get(context)['myPlugin'];`.  I'd personally prefer the latter because a) it requires no changes to BotState and b) I think developers are smart enough that they'll likely figure out they should do that without me even having to tell them they should.  Let's not forget that middleware is a 300 level concept.

**Comment by billba** [comment]
> I think developers are smart enough that they'll likely figure out they should do that without me even having to tell them they should.

It's not helpful to cast this in terms of smart vs. not smart. Some very, very smart people could not figure out how v3 worked.

**Comment by Stevenic** [comment]
We added the ability to pass a `namespace` tag into `ConversationState` and `UserState`. I believe that largely addresses this so closing but let me know if you disagree.
