### ISSUE TITLE
botbuilder-ai  - LuisRecognizer is replace "." with "_" when intents are fetched

### ISSUE THREAD

**Issue by Harry17** [microsoft/botbuilder-js#1423]
## Versions
What package version of the SDK are you using. - 4.6.1
What nodejs version are you using -10.5.0
What browser version are you using - Chrome Version 72.0.3626.121 (Official Build) (64-bit)
What os are you using Windows 10

## Describe the bug
Give a clear and concise description of what the bug is.
I am using LuisRecognizer  is get intents from Cognitive services.
My intent is named "Employee.Roster" but LUISRecognizer is discovering it as "Employee_Roster"
replacing a dot "." with Underscore "_".

## To Reproduce
LUIS configure an intent with "User.Live"
configure LuisRecognizer  as -
const dispatchRecognizer = new LuisRecognizer({
            applicationId: process.env.LuisAppId,
            endpointKey: process.env.LuisAPIKey,
            endpoint: `https://${ process.env.LuisAPIHostName }.api.cognitive.microsoft.com`
        }, {
            includeAllIntents: true,
            includeInstanceData: true
        }, true);

const recognizerResult = await dispatchRecognizer.recognize(context);

            // Top intent tell us which cognitive service to use.
            const intent = LuisRecognizer.topIntent(recognizerResult);
Run the nodejs 
Debug and check if intent in code is "User.Live" OR "User_Live"
## Expected behavior
Give a clear and concise description of what you expected to happen.

When LuisRecognizer  recognize the intent it should give intent as it is and not replace a dot with underscore.

## Screenshots
Please below debug watch 
![image](https://user-images.githubusercontent.com/7355959/69006846-4b7eeb80-0989-11ea-8868-d441d61f762d.png)

Also here is my intents configured in Azure LUIS

![image](https://user-images.githubusercontent.com/7355959/69006915-6d2ca280-098a-11ea-81e9-e68595d8b165.png)

## Additional context

[bug]

**Comment by mdrichardson** [comment]
@Harry17 This is less of a Node problem and more about how LUIS serializes the JSON. That being said, the closest thing to documentation on this is [found here](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-boundaries#object-naming). However, it doesn't specifically mention periods.

I filed a bug on this some time ago, but it's more of a backlog item. (MSFT Internals, found [here](https://luisai.visualstudio.com/LUIS/_queries/edit/8917/?triage=true))

My guess is that LUIS replaces all separator characters with underscores for consistency. There may be some trouble parsing some due to the various ways the JSON gets serialized and deserialized.

That being said, as you're now aware of the behavior, I'd either account for it in your code or change your intent names in LUIS. If you're worried about this happening with other intent names, you could use RegEx matching in your code when you look for intents.

I know, not ideal, but the only part of this that's likely to change is updated documentation, which I'll put a request in for.

Again, this is being tracked internally, so I'll close this issue.

**Comment by harry17preet** [comment]
thanks @mdrichardson  for the info and good to know that its on MS backlog.
