### ISSUE TITLE
applyConversationReference issue

### ISSUE THREAD

**Issue by ubreddy** [microsoft/botbuilder-js#1455]
## Versions
What package version of the SDK are you using. V4.6.1
What nodejs version are you using : v11.5
What browser version are you using : na
What os are you using : windows 10

## Describe the bug
**Describe the bug**
```

let ref = TurnContext.getConversationReference(context.activity)
let newActivity = TurnContext.applyConversationReference({type: 'message'}, ref)
let newRef =  TurnContext.getConversationReference(newActivity)

// expect newRef to be same as ref

```
The newRef and ref have interchanged bot and user properties.

**Comment by v-kydela** [comment]
@ubreddy - I'm assuming your `context.activity` contains an incoming activity. You can see in the [SDK reference](https://docs.microsoft.com/en-us/javascript/api/botbuilder-core/turncontext?view=botbuilder-ts-latest#applyconversationreference-partial-activity---partial-conversationreference---boolean-) that `isIncoming` is `false` by default because `applyConversationReference` is mostly meant to be used on outgoing activities, and this is supposed to switch the `from` and `recipient` properties so that the activity can be sent to the user. If you want to apply a conversation reference to an incoming activity then you should set `isIncoming` to `true`.

Does this resolve your issue?

**Comment by ubreddy** [comment]
yes. Thank you.
Uday 

    On Saturday, 30 November, 2019, 02:17:34 am IST, Kyle Delaney <notifications@github.com> wrote:  
 
 
@ubreddy - I'm assuming your context.activity contains an incoming activity. You can see in the SDK reference that isIncoming is false by default because applyConversationReference is mostly meant to be used on outgoing activities, and this is supposed to switch the from and recipient properties so that the activity can be sent to the user. If you want to apply a conversation reference to an incoming activity then you should set isIncoming to true.

Does this resolve your issue?
