### ISSUE TITLE
Telegram message sent via inline_query results in error

### ISSUE THREAD

**Issue by stevkan** [microsoft/botbuilder-js#1515]
When "Inline mode" is enabled for a bot and a user sends an inline keyboard message (i.e. direct/personal message => @some_bot [some message]) from another channel or conversation to the bot then this error is produced:

`[onTurnError]: TypeError: Cannot read property 'toLowerCase' of undefined`

The inline keyboard message sends an inline_query object in channelData that is structured differently. As such, it contains a `query` property in place of the `text` property that contains the user's input.

In addition, the activity.text property is missing under this scenario. Any mapping that may be taking place between `query` and `activity.text` properties cannot occur.

Activity with message:
```
{ 
  type: 'message',
  id: 'CTL53hXJ4EN',
  timestamp: 2019-08-08T01:47:35.608Z,
  serviceUrl: 'https://telegram.botframework.com/',
  channelId: 'telegram',
  from: { id: '803613355' },
  conversation: { isGroup: false, id: '803613355' },
  recipient: { id: 'some_bot', name: 'some_bot' },
  text: 'hi',
  channelData:
   { update_id: 344945158,
     message:
      { message_id: 152,
        from: [Object],
        chat: [Object],
        date: 1565228855,
        text: 'hi'
      }
   }
}
```

Activity with inline_query:
```
{
  type: 'message',
  id: '3451493079534591354',
  timestamp: 2019-08-08T01:46:18.524Z,
  serviceUrl: 'https://telegram.botframework.com/',
  channelId: 'telegram',
  from: { id: '803613355' },
  conversation: { isGroup: false, id: '803613355' },
  recipient: { id: 'some_bot', name: 'some_bot' },
  channelData:
   { update_id: 344945157,
     inline_query:
      { id: '3451493079534591354',
        from: [Object],
        query: 'hi',
        offset: ''
      }
   }
}
```

**Comment by cleemullins** [comment]
@stevkan - is this something we can fix or close out?

**Comment by srinaath** [comment]
@stevkan Any update on this ticket or should we close it out.

**Comment by CoHealer** [comment]
Adding @stevengum to comment as to whether this issue is indeed sympton/repro of microsoft/BotBuilder-Samples#1728

**Comment by stevengum** [comment]
The issue in microsoft/BotBuilder-Samples#1728 is that responding to a prompt in the core-bot sample with an activity that doesn't have `Activity.Text` will blow up.

While the problem is similar, I'm hesitant to close this out on the notion that this bug is the same as that core-bot sample specific bug.

@stevkan didn't mention a specific sample, so I'm assuming this is a generalized problem when using Inline Keyboards on Telegram. 

I think that the current behavior regarding the channel is correct, and that there isn't anything to do in the SDK or on the service.

For channel specific features (e.g. inline keyboard), the data should be found in `Activity.ChannelData`. We could request that the Service team takes the inline_query from ChannelData and maps it to Activity.Text, but I think this would be a slippery slope as we need to do it for multiple channels where similar scenarios exist. 

Ultimately, I think this is a issue solved by _documentation for 3rd party channel specific behavior_, not by any changes in either the SDK or Service.

**Comment by stevkan** [comment]
@stevengum, you are correct. It was discovered while testing outside of any provided sample.

**Comment by scheyal** [comment]
For SLA tracking, FYI it is not a customer reported issue.

**Comment by clearab** [comment]
@Kaiqb This issue is assigned to you and has been open for quite some time. Is this being actively worked?

**Comment by JonathanFingold** [comment]
@stevkan Can you submit a PR with needed changes to the [Implement channel-specific functionality](https://docs.microsoft.com/azure/bot-service/bot-builder-channeldata) article? Please include descriptions for the entities that Telegram might send in an activity and any that Telegram might accept from a bot activity.

Bonus points. I know the email channel data information is out of date, but we don't know what the schema is for that one, so we can't fix it. If you can fix that one while you're in this article, that would be great!

**Comment by stevkan** [comment]
Meant to update this thread that I'm working on this.

**Comment by stevkan** [comment]
Updated docs with PR [#2014](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2014). Per conversation with @JonathanFingold, am not updating the email schema as more information is needed from the Services team.
