### ISSUE TITLE
Logging Personal Information in Application Insights Telemetry

### ISSUE THREAD

**Issue by anishjaindev** [microsoft/botbuilder-js#1535]
I am trying to use botbuilder-applicationisights module for telemetry logging of Bot activities, QnA Maker & LUIS traces into Application Insights. However, the personal information like text, user name is not logged.

Is there any flag which I have to enable so that this logging can be enabled.

**Comment by mdrichardson** [comment]
@anishjaindev This isn't something provided by the SDK due to privacy laws, therefore, there's also no flag to enable it. However, you could easily add this functionality in yourself by re-creating [the ApplicationInsightsTelemetryClient class](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts#L63), and then changing what [`addBotIdentifiers`](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts#L127) collects--you can see that it does not grab `activity.from.name`.
