### ISSUE TITLE
[PORT] update adaptive inputs to set inputHint = expectingInput 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1776]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3427

ref to this issue: #3344

At first, LG `ActivityFactory` use `MessageFactory.Text()` to generate message activity result from LG output, but `MessageFactory.Text()` would inject `inputhint = expectingInput ` into activity, and the prompt of input relies on this feature.

 Then we found there is no reason to add `inputhint` into pure text activity, so we removed it in this pr: #3382. 

At the same time, we should update adaptive inputs to set `inputHint = expectingInput` whenever we are issuing a prompt or reprompt (unrecognized/ invalid prompt).

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive

[P0]

**Comment by Danieladu** [comment]
adaptive issue

**Comment by edwgj** [comment]
Hi, when using direct line speech channel and the user uses the microphone, the bot speaks and automatically activates the microphone when reaching an inputDialog action. I think the mic wouldn't activate if I changed the inputHint from 'expecting' to 'ignoring' in the prompt's activity, but I cannot change the 'expecting' value. Is there another way to prevent the mic from being activated? Thanks

**Comment by joshgummersall** [comment]
@Danieladu or @luhan2017 could you take a look at what @edwgj is asking?

**Comment by edwgj** [comment]
@Danieladu the value of inputHint cannot be changed using the LG template within an inputDialog prompt:
`new TextInput()
{
  Property = 'turn.user_input',
  Prompt = new ActivityTemplate("${myTemplate()}")
}`
I think this is due to the update mencioned by @tomlm : "At the same time, we should update adaptive inputs to set inputHint = expectingInput whenever we are issuing a prompt or reprompt (unrecognized/ invalid prompt)."

I know we expect a user input after issuing an inputDialog prompt, but what if I don´t want the microphone to be automatically activated when using voice with direct line speech?

**Comment by Danieladu** [comment]
Oh. I find it. The inputHint would be overridden with `ExpectingInput` in the prompt property.
You mean the customer just wants the bot accept "text" content, but disable "speak" content? 
@tomlm  @Stevenic any idea about this one?

**Comment by edwgj** [comment]
To better explain this, let's say a bot using adaptive dialogs and direct line speech channel on web chat do the following:
1. User click on mic and speech something
2. The bot ask for user name with the TextInput dialog, so it speaks 'what's your name' and the mic is automatically activated due to the `expectingInput`
3. The user has to speak his/her name

How could I prevent the mic to be activated, so the user can choose to write the name or click on mic again?

**Comment by Danieladu** [comment]
@edwgj 
I have filed an issue to enable the customer to customize the inputhint value.
https://github.com/microsoft/botbuilder-js/issues/3195
So that value of inputHint can be changed using the LG template within an inputDialog prompt.
Close this one and track it in the new issue.

**Comment by edwgj** [comment]
@Danieladu  I can see the update, thanks a lot
