### ISSUE TITLE
[PORT] fix memory scope for class memory scope to evaluate expressionProperties

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1818]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3463

#3460 
Changes:
* Add **IExpressionProperty** to make it easier to work with untyped expression properties
* Add internal class **ExpressionPropertyBinder** which evaluates properties that are expressionProperties.
* Change **ClassScope** and **DialogClassScope** to use **ExpressionPropertyBinder** 
* Remove some legacy unused classes 
* Fix DialogStateManager to take in configuration of memory scopes
* Add unit tests for coverage of bug.

# Changed projects
* AdaptiveExpressions
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder.Dialogs.Tests

[adaptive,bug]

**Comment by Stevenic** [comment]
Needs porting

**Comment by cleemullins** [comment]
@chon219, @vishwacsena Can we get an update on this?

**Comment by chon219** [comment]
> @chon219, @vishwacsena Can we get an update on this?

I'm working on this.

**Comment by chon219** [comment]
We have to check if a property in dialog is  expression property or not, but we don't want to introduce dependency to AdaptiveExpression in botbuilder-dialogs.
@Stevenic Do you know which is the best practice to implement this part since it seems to be quite different from C#'s.
And do we need to push this issue to R9 since it is not a blocking issue to our major functionally?

**Comment by sgellock** [comment]
pulling back so we can get this done in time for RC builds.
