### ISSUE TITLE
Discussion: how should middleware inject activities into the outgoing stream?

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-js#187]
Currently we let middleware use `Array.splice()` to modify the outgoing activities array in `onSendActivities()`.  Issue #109 raised a few concerns about needing to use splice() and proposed other options worth discussing. Opening a new issue for the debatable part as the bug originally reported in #109 should be fixed.

**Comment by codefoster** [comment]
In m3, in a Middleware's `onTurn` method, it appears we have `context.activity` now. Does that mean that this point is moot and we don't act on sets of activities anymore or am I missing something?

**Comment by Stevenic** [comment]
The question is really around the handling of `context.onSendActivities()`  as in below:

```JS
context.onSendActivities(async (context, activities, next) => {

    // Do something with activities

    await next();
});
```

**Comment by codefoster** [comment]
Okay, well, I like immutability as much as the next guy, but if middleware in general is something that mutates state, then it doesn't seem so bad to _modify_ the activities collection. If all middleware can be immutable, though, I suppose that's ideal and we should generate a new activities collection and pass that to the `next` function.. If I call `next()` and that's really just a shortcut for calling `next(activities)` then we don't have to feel bad about having a function overload because it's not a hack... it's just a default. Hope that makes sense. Just opinion.

**Comment by Stevenic** [comment]
My concern about changing the signature for `next()` is that it will be the only case where you pass an argument to next() and it's going to be super easy for you to forget to do so.  If you're not using TypeScript you're not going to have a compiler there to tell you that you forgot to do so.  

We're already running into issues around forgetting to pass in the context object (issue #189).  In v3 this issue was largely limited to prompts but now we have tons of things that take a context object. Our doc writers are mostly JavaScript developers and I've already spent several hours having to help them track down bugs related to them a) failing to call `await` on something before returning, and b) forgetting to pass in a context object to something expecting one.  Without a compiler in the mix both can be super tough to track down.   The context object issue we can address at runtime with better argument checks but I'm not sure what to do about the await issues...

**Comment by Stevenic** [comment]
Closing old discussion
