### ISSUE TITLE
Shouldn't we should use return statement here? 

### ISSUE THREAD

**Issue by BhuwanBhaskar** [microsoft/botbuilder-js#2222]
https://github.com/microsoft/botbuilder-js/blob/001ecb57f7762ee1863fcb8793e1cd96c636f118/libraries/botbuilder/src/teamsActivityHandler.ts#L166

Switch case would fall through second case as well which would be wrong

**Comment by cleemullins** [comment]
@v-kydela - any update on this?

**Comment by cleemullins** [comment]
@stevenic to look at this.

**Comment by v-kydela** [comment]
@cleemullins - Sorry, Chris. I didn't think support was supposed to take this because it seemed like an issue for your team. The customer appears to be right that execution would fall through the first case into the second in a subclass of `TeamsActivityHandler`, but in that class both cases are designed to throw "not implemented" errors.

**Comment by Stevenic** [comment]
Good catch. There's a PR out there with a fix.
