### ISSUE TITLE
TeamsInfo.getMembers return also a property named "objectId"

### ISSUE THREAD

**Issue by SchleSha** [microsoft/botbuilder-js#2257]
Hi,

I'm using V4 bot framework with typescript.

I'm using getTeamMembers function in my bot. 

I've been looking at the response of type TeamsChannelAccount[] and I noticed that the response object should also contain also a property named "objectId". 

It seems like it is not documented nor mentioned in the official docs. 
It would be nice if you can add to the TeamsChannelAccout interface and to your doc.

Thanks

**Comment by mdrichardson** [comment]
@SchleSha 

What do you mean it *should* contain the objectId?

`TeamsChannelAccount` schema can be found [here](https://github.com/microsoft/botbuilder-js/blob/a5cd037f79310623bbbb04a5bf8908e8346058b7/libraries/botframework-schema/src/teams/index.ts#L158). As you can see, it extends `ChannelAccount`, [here](https://github.com/microsoft/botbuilder-js/blob/54e4c2ded75436c00fe182dcb4c0c077f45741bc/libraries/botframework-schema/src/index.ts#L90).

Neither of these contain `objectId`, although `ChannelAccount` contains `aadObjectId`, which won't exists for users--only for bots.

**Comment by SchleSha** [comment]
Hi,

Thanks for your quick response. 

What I tried to say is that I noticed that the response contains this property, which is not documented anywhere.

The response look like that: 
```
{
 id: 
 name: 
 objectId:
 email:
 userPrincipalName:
 tenantId:
 userRole:
 aadObjectId:
}
```

Thanks

**Comment by mdrichardson** [comment]
@SchleSha Ah, I see what you mean. Unfortunately, `objectId` has now been part of the response for awhile, so removing it would be a breaking change. Since it doesn't exist in the C# SDK (because the object gets typecast to `TeamsChannelAccount`, which doesn't happen the same way in TS/JS), it won't be added to official docs, either.

All that being said, please use `aadObjectId` instead of `objectId`.
