### ISSUE TITLE
checkForVersionChange() in dialogContainer.ts throws "Version change detected"

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/botbuilder-js#2294]
## Versions

What package version of the SDK are you using.? - NODE SDK botbuilder 4.8.0
What nodejs version are you using? - v13.6.0

## Describe the bug
Today we had a production downtime due to following error from method checkForVersionChange() in this class [dialogContainer.ts](https://github.com/microsoft/botbuilder-js/blob/d1df6cbfbd9eadf41b7592dc7183d8a34f65a982/libraries/botbuilder-dialogs/src/dialogContainer.ts)

We didn't make any library changes or any updates to package.json were made. Looks like method checkForVersionChange() is newly introduced in botbuilder-dialogs package version 4.9.X. 

As remedy, we rollbacked to older version of bolbuilder as shows bellow image

![image](https://user-images.githubusercontent.com/32375467/83456334-22a1dd80-a425-11ea-8c9c-22e27e98dc23.png)

## To Reproduce
Just buid nodejs SDK bot using latest versions of following packages and, use MS Teams channel 

		"botbuilder": "^4.8.0",
		"botbuilder-ai": "^4.8.0",
		"botbuilder-applicationinsights": "^4.8.0",
		"botbuilder-azure": "^4.8.0",
		"botbuilder-dialogs": "^4.8.0",
		"botbuilder-skills": "^4.4.9",
		"botbuilder-solutions": "^4.4.9",

## Expected behavior
We need to know how to handle Version changes gracefully. 

## Additional context
What's recommended fix for this?
When we downgrade to a version of a package how do we know it's right thing to do because, some other package might not be compatible with old version.  

[bug]

**Comment by mdrichardson** [comment]
@rjgmail88 Is the error you're receiving, "`Version change detected for '${this.id}' dialog.`" ? If so, [that's intentional](https://github.com/microsoft/botbuilder-js/blob/d1df6cbfbd9eadf41b7592dc7183d8a34f65a982/libraries/botbuilder-dialogs/src/dialogContainer.ts#L69). `checkForVersionChange()` doesn't check for changes in the SDK version; [it checks to see if a user has resumed a conversation after the bot was updated and the dialogs have changed](https://github.com/microsoft/botbuilder-js/blob/d1df6cbfbd9eadf41b7592dc7183d8a34f65a982/libraries/botbuilder-dialogs/src/dialogContainer.ts#L50). You can ignore this error or implement a handler for it, such as alerting the user and restarting all dialogs.

That being said, I also see that some of your `botbuilder-*` packages don't match. Please make sure they all use the same version.

You should be able to safely upgrade the minor versions of packages (`4.*`), but you should pretty much never downgrade them from a working bot.

**Comment by rjgmail88** [comment]
@mdrichardson, thanks for your input on this. Any examples on this how do we handle this? or other customers are handling. The reason to ask is, in prod CICD process we actually redeploy and restart the nodejs bot app. So after that every message from a user to bot is new session/activity so it should not break on version.   

Another thing we already have in place is called Global exist commands like 'cancel' , exist , stop which calls cancelAllDialogs() but, when end users used this commands we bot keep running to same issue mentioned here. It was like bot was fully stuck. 

Did you mean, have a global error handler in our bot specific for this use case and just call cancelAllDialogs()?

All of them are 4.7.x except botbuilder-skills and  botbuilder-solutions because 4.4.x is the max available as per 
[https://www.npmjs.com/package/botbuilder-skills](https://www.npmjs.com/package/botbuilder-skillsl)

Can you suggest best versions for all botbuilder packages we should use ?

**Comment by mdrichardson** [comment]
@rjgmail88 First, my mistake on the mismatched package versions--you're right. As far as "best" versions...use the newest as much as possible.

There are no samples for how to use `checkForVersionChange()`, currently. It's pretty new and entirely up to you what you want to do with it. You can safely ignore it, provided you have an [`onTurnErrorHandler`](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/13.core-bot/index.js#L37). If you want to handle it, since [`DialogContainer` emits an event](https://github.com/microsoft/botbuilder-js/blob/d1df6cbfbd9eadf41b7592dc7183d8a34f65a982/libraries/botbuilder-dialogs/src/dialogContainer.ts#L66), in your `ActivityHandler` class, you can use use [`onEvent`](https://github.com/microsoft/BotBuilder-Samples/blob/3fa33de7007ccb82a7766f615ee62bee21b40880/samples/javascript_nodejs/23.facebook-events/bots/facebookBot.js#L27) (this sample isn't for the `DialogEvents.versionChanged`, but it's the only one we have that uses `onEvent`)

**Comment by rjgmail88** [comment]
Sounds good. Thank you.
