### ISSUE TITLE
Mask User Input  

### ISSUE THREAD

**Issue by saranyuavh** [Microsoft/botbuilder-js#237]
During a Dialog in Bot-Framework, adding the feature of masking the user input(response to Prompts) would be very very helpful.

**Comment by iMicknl** [comment]
Why and on which channel? Do you mean that you want to have the user input masked in the WebChat, so like a password field? At the moment there is a discussion about this in another repository. https://github.com/Microsoft/BotFramework-WebChat/pull/976. However I wouldn't recommend that.

Or do you want to filter out credit card information (for example) from the text response. In order to do something like that, just writing a custom middleware with some regexes should do the job already.

**Comment by saranyuavh** [comment]
I have connected a database to the bot which has users database and users can login though the bot dialog itself where I am using prompts.text, therefore, I want to mask the user input while the user is responding to the prompt "builder.Prompts.text("Enter your Password")". Once user is authenticated, a query can be raised according to his question or selected suggestion.

**Comment by iMicknl** [comment]
I think this is something that has to be implemented by the channels itself. (so WebChat and Microsoft Teams). In my previous reply I already linked to a possible solution for the webchat, where they also have a discussion.

Especially on Microsoft Teams, I believe there are better options for authenticating your users instead of sending a plain text password to your bot. I would recommend using a sign in card for this which sends you to an external website to perform the login or even better use OAuth to implement your custom login provider.

**Comment by Stevenic** [comment]
Thanks @iMicknl ... Agree on all accounts. This is something that would have to be implemented by the channels and you should probably use oAuth instead.

**Comment by vishwacsena** [comment]
@compulim can you evaluate this as possible feature for webchat?
