### ISSUE TITLE
DialogSet.createContextAsync(): the dialog set was not bound to a stateProperty when constructed.

### ISSUE THREAD

**Issue by kostyaVyrodov** [microsoft/botbuilder-js#2473]
## Versions
What package version of the SDK are you using.

-  "botbuilder": "4.9.2",
- "botbuilder-dialogs": "^4.9.2",

What nodejs version are you using

- 12.16.3

What browser version are you using

- MS Teams in chrome

What os are you using

- Mac OS

## Describe the bug
`await this.dialogs.createContext(context);` throws DialogSet.createContextAsync(): the dialog set was not bound to a stateProperty when constructed.

## To Reproduce

```
import { TurnContext, StatePropertyAccessor } from "botbuilder";
import { ComponentDialog, DialogSet } from "botbuilder-dialogs";
import { HelpDialog } from "./help";
import { HelpDialog2 } from "./help2";

export class RootDialog extends ComponentDialog {
    constructor() {
        super('Root');

        this.addDialog(new HelpDialog('Help1'));
        this.addDialog(new HelpDialog2('Help2'));

        this.initialDialogId = 'Root';
    }

    async run(context: TurnContext, accessor: StatePropertyAccessor<any>) {
        try {
            // Throws DialogSet.createContextAsync(): the dialog set was not bound to a stateProperty when constructed.
            // Because botbuilder-dialogs/src/dialogContainer.ts 
            // public readonly dialogs = new DialogSet(undefined);
            const dialogContext = await this.dialogs.createContext(context);
            await dialogContext.beginDialog('Help2');
        } catch (error) {
            console.log(error);
        }
    }
}
```

## Expected behavior
Should succesfully create dialogContext

## Screenshots
![image](https://user-images.githubusercontent.com/15310397/86340869-3af05c80-bc5e-11ea-929a-e430d9b2e317.png)

![image](https://user-images.githubusercontent.com/15310397/86341179-9fabb700-bc5e-11ea-8d3b-2a618ebadf52.png)

## Additional context

[bug]

**Comment by v-kydela** [comment]
Thank you for the feedback, @kostyaVyrodov 

The reason why a dialog container's dialog set doesn't need its own state property accessor is because the dialog container is itself expected to be added to a dialog set, and only the root dialog set will need a state property accessor. Allowing each dialog container to have its own state property accessor could result in different dialogs belonging to different state properties even though they're on the same stack, which wouldn't make any sense.

Rather than trying to pass a state property accessor to the dialog container's dialog set, you should create a root dialog set with a state property accessor and add your dialog container to it. Then you can create a dialog context from that root dialog set.

Also note that a component dialog's initial dialog ID is the child dialog that begins when the component dialog begins, so you should use the ID of a dialog in the component dialog's dialog set. You should not use the component dialog's own ID as its initial dialog ID because the component dialog is not a child of itself.

To fix your problem, please read the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog) and follow the [samples](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/13.core-bot) that are available to you. If you have any questions, please ask them on [Stack Overflow](https://stackoverflow.com/help/how-to-ask). My team sees every question with the `botframework` tag.
