### ISSUE TITLE
=concat() causes a validation error

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-js#2780]
## Describe the bug

Composer throws a validation error if an expression is using concat as the returned value.

For example, use =concat('foo','bar') a field that expects a string.

![Screen Shot 2020-09-11 at 3 39 48 PM](https://user-images.githubusercontent.com/729873/92971132-82a51880-f445-11ea-9f1e-f9bcec746301.png)

## Version

1.1.1

## To Reproduce

1. Add an HTTP request step
2. In the URL field, set the type to expression
3. Set the value to =concat('foo','bar')

you will see a validation error

### expected response

this should be a valid value since concat returns a string.

**Comment by cwhitten** [comment]
Transferring to botbuilder-js

**Comment by Danieladu** [comment]
@cwhitten The `concat` returns 24 is because Expression library uses "bit field" of enum. (Something like `IntFlag` in python).  
Using this feature, the built-in function can support multiple return types.
For example:
 The return type of `concat` is String or Array, corresponding to the return type enum is 24 (8 + 16), 8 presents String, and 16 presents Array.

So, maybe should adjust the validation of returntype in Composer?

**Comment by cwhitten** [comment]
Thank you @Danieladu 

@boydc2014 @lei9444 should this return type instead be exported from `adaptive-expressions`?

**Comment by lei9444** [comment]
> Thank you @Danieladu
> 
> @boydc2014 @lei9444 should this return type instead be exported from `adaptive-expressions`?

hi, @cwhitten I am working on the return type in composer last week, and I will have a PR to fix it today.
