### ISSUE TITLE
Investigate OAuth functionality in Streaming scenarios

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2785]
.NET issue with additional context: https://github.com/microsoft/botbuilder-dotnet/issues/4673
.NET PR to `main`: https://github.com/microsoft/botbuilder-dotnet/pull/4680

.NET tl;dr - In R10 the TokenResolver class was refactored which resulted in a polling operation blocking the thread and causing disconnections in streaming scenarios (Direct Line ASE, Direct Line Speech)

This issue tracks investigating the OAuth and Streaming intersection in the JS SDK. It's unclear if this issue also exists or if the functionality currently works in JS.

**Comment by stevengum** [comment]
@mrivera-ms and @JuanAr, any updates on this?

**Comment by stevengum** [comment]
If this isn't going to land for R11, @mrivera-ms can you remove the milestone? Thanks!

**Comment by denscollo** [comment]
We investigated the issue and concluded that it is unlikely that this issue is present in JS. 
 
First, the issue was introduced in BotBuilder-DotNet by the PR#4141 the 2020-06-25 and it wasn't ported to BotBuilder-JS. Also, note that the latest update in tokenResolver.ts at 2020-03-06. 
Also, the issue in BotBuilder-DotNet was caused by blocking on polling operations when using `Task.waitAll()`, and we did not find any part of code in tokenResolver.ts that we think could block the thread. 
At last, tokenResolver.ts unit tests for getting the token, getting it on a second try, ending the polling, and changing the polling interval, pass. 
 

![imagen](https://user-images.githubusercontent.com/27219455/97304578-adeb9780-183a-11eb-9620-c85d069ab705.png)


 
We tried to test the class with a streaming scenario such as Direct Line ASE or Direct Line Speech, but we could not make a bot sample work with these tools. Direct Line ASE documentation refers to use the `.bot` file of the bots, that is deprecated. Also, the Direct Line Speech documentation only has information on how to implement it to a C# bot. 

 

If you can point us to any resource with instructions on how to set up these test scenarios we would be happy to try again.

**Comment by joshgummersall** [comment]
@denscollo can you send us a link to the Directline ASE documentation that references `.bot` files? We would like to get that updated.

**Comment by ceciliaavila** [comment]
> @denscollo can you send us a link to the Directline ASE documentation that references `.bot` files? We would like to get that updated.

Hi @joshgummersall , this is the [link](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-node-bot?view=azure-bot-service-4.0) to the documentation that references the .bot files. 
Thanks.
