### ISSUE TITLE
Verify if Streaming bots can call skills

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2918]
"Parity Investigation Tracking" issue for https://github.com/microsoft/botbuilder-dotnet/issues/4254.

It's unclear if Streaming bots in JS can successfully call Skills.

**Comment by stevengum** [comment]
@mdrichardson and @Zerryth do the two of you want to decide who investigates this in R12?

**Comment by Zerryth** [comment]
@stevengum I'll volunteer as tribute to investigate in R12, since I've worked with streaming in js + skills

**Comment by Zerryth** [comment]
Update: still working on this. I've run into this unexpected 200 response error:

```
webchat.js:2 WebSocket connection to 'wss://westus2.convai.speech.microsoft.com/api/v3?language=en-US&format=simple&Ocp-Apim-Subscription-Key=89eaxxxxxxxxxxxxxxxxxxxxxxxxxxxx&X-ConnectionId=271FC0DE84D1487C85CFC53636114BD8' failed: Error during WebSocket handshake: Unexpected response code: 200
```
However this is just trying to connect to DL Speech and not even specifically connecting to a skill yet, I believe?
____

Repro:
### **1. Get sample 80.skills-simple-bot-to-bot deployed to Azure**
Works properly *without* streaming enabled.

### **2.  Enable Streaming in Bot**

* Add streaming endpoint to root (consumer) bot `index.js`
```js
// Listen for Upgrade requests for Streaming.
server.on('upgrade', (req, socket, head) => {
    // Create an adapter scoped to this WebSocket connection to allow storing session data.
    const streamingAdapter = new BotFrameworkAdapter({
        appId: process.env.MicrosoftAppId,
        appPassword: process.env.MicrosoftAppPassword
    });
    // Set onTurnError for the BotFrameworkAdapter created for each connection.
    streamingAdapter.onTurnError = onTurnErrorHandler;

    streamingAdapter.useWebSocket(req, socket, head, async (context) => {
        // After connecting via WebSocket, run this logic for every request sent over
        // the WebSocket connection.
        await myBot.run(context);
    });
});
```

* Root bot's App Service > Configuration > Turn Web Sockets on
![image](https://user-images.githubusercontent.com/35248895/97365137-6c6ee280-1862-11eb-9d8b-3fabd701db5d.png)

* Check Enable Streaming Endpoint in Bot Channels Registration for root bot
![image](https://user-images.githubusercontent.com/35248895/97364986-2285fc80-1862-11eb-9c22-dd7d8b682204.png)

### **3.  Use a speech client like sample to talk to streaming-enabled root bot**

Using either [bf-wc/samples/03.speech/a.direct-line-speech](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/a.direct-line-speech) or [Windows Voice Assistant Client](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/blob/master/clients/csharp-wpf/README.md), try talking to bot > receive "`failed: Error during WebSocket handshake: Unexpected response code: 200`" error

___

There seems to be issues with this occurring in the past, though the reason exactly remains unknown:
* [WebSocket connection immediately closed on macOS](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/221)
* [Directline speech - web socket ends with 200 response](https://github.com/microsoft/BotFramework-WebChat/issues/3407)

**Comment by Zerryth** [comment]
Update 2: Ok, one way you can get passed the unexpected 200 response error is by just creating a new cognitive service Speech key, and use that subscription key in the client (i.e. Web Chat, Windows Voice Assistant client) when requesting a DL Speech token.

Now however it looks like it will `WebChat.createDirectLineSpeechAdapters`, however it doesn't connect to the streaming bot--or it closes the socket right away. Hard to tell, there aren't any errors. Clicking the mic is clickable, but it stops listening right away.

*WebChat using DL Speech adapter doesn't connect to bot*
![image](https://user-images.githubusercontent.com/35248895/97466208-15b7e600-1900-11eb-9475-d9c223dd2dae.png)


<details>
    <summary>Click to see a.direct-line-speech code, modified with subscription key.</summary>

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Using Direct Line Speech</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Direct Line Speech adapter set is only available in full bundle -->
    <!--
      This CDN points to the latest official release of Web Chat. If you need to test against Web Chat's latest bits, please refer to pointing to Web Chat's MyGet feed:
      https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits
    -->
    <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <style>
      html,
      body {
        height: 100%;
      }

      body {
        margin: 0;
      }

      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>

  <body>
    <div id="webchat" role="main"></div>
    <script>
      (async function() {
        const adapters = await window.WebChat.createDirectLineSpeechAdapters({
          fetchCredentials: {
            region: 'westus2',
            subscriptionKey: 'cdxxxxxxxxxxxxxxxxxxxxxxxxxxxx6a'
          }
        });

        console.log('adapters ', adapters);

        // Pass the set of adapters to Web Chat.
        window.WebChat.renderWebChat(
          {
            ...adapters
          },
          document.getElementById('webchat')
        );

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>
```

</details>

___

I'll need to debug into WC/SDK to see more, given there aren't any errors, however pausing a bit to work on a different, customer-reported issue.

**Comment by joshgummersall** [comment]
@Zerryth do you have an update on this issue? Next steps and suggestions would be helpful.

**Comment by Zerryth** [comment]
For sure skills don't work with default DeliverMode, however still need to plug in DeliveryMode.ExpectReplies
(which I paused doing to fix a customer-reported issue in don't OAuthPromt/OAuthInput)
Digging into that today

**Comment by Zerryth** [comment]
Ok, so I set up:
* sample 81., which uses skills dialog
* configured it to use DL Speech
* used WebChat sample 03.speech/a.direct-line-speech as the channel to speak to the bot

The above does not work for the default DeliveryMode, as mentioned earlier, and we know why that happens (it can't find the streaming session that the original parent adapter connected to, because of the way we respond back with another request)

Currently, when changing the activity in `skillDialogArgs` to `DeliveryMode.ExpectReplies`, **it does not work**:

![image](https://user-images.githubusercontent.com/35248895/98183476-0961f900-1ebd-11eb-9dc1-f8ab8d15bcc0.png)

^ conversation stops there. It does enter the SkillDialog's logic, so something's going awry in the response from Skill -> Parent

Still don't know why yet. Stepping through the SDK to hunt down the issue still

**Comment by joshgummersall** [comment]
@Zerryth thanks for the details! I think this issue can be closed once you can identify the problem (or set of problems) and create a separate Github issue to track the fix (or fixes).

**Comment by Zerryth** [comment]
OK! So streaming + skills in JS **do** work! 🎊 --sorta.
___
### Expected
*Emulator, Default DeliveryMode*
![image](https://user-images.githubusercontent.com/35248895/98409913-878ede80-2028-11eb-9a30-42df7339a826.png)
![image](https://user-images.githubusercontent.com/35248895/98410173-05eb8080-2029-11eb-9fd9-4b723c634c1f.png)

* Saying "book flight" is the first message from the user, that will get forwarded to the skill.
* Notice how the response to book flight is the LUIS result, and a question of "To what city would you like to travel?"
* Additionally the traces from the first response to the skill actually show up as well

### Actual
*Emulator, DeliveryMode.ExpectReplies*
![image](https://user-images.githubusercontent.com/35248895/98410417-7eead800-2029-11eb-9001-f1edc881677f.png)

*Web Chat + DL Speech, DeliveryMode.ExpectReplies*
![image](https://user-images.githubusercontent.com/35248895/98410463-95912f00-2029-11eb-91c4-4170e2bef6ac.png)

* Notice how in the actual, *the first batch of buffered activities to reply with that contain the skill's first response to the user's "book flight" message are gone*
   * 2 messages containg LUIS result + asking user "To what city..." is missing
   * Several traces are not there 
   * Stepping through there are supposed to be 5 activities sent total, none make it through
* However, since I happen to know what the dialog is expecting, I notice that I could continue the dialog by telling it a city name
   * Then you notice the buffered replies actually come through

___
### Conclusion:
* If you want to use skills with streaming, you need to use `DeliveryMode.ExpectReplies`, as the default mode won't work
* Skills + streaming works, but in a buggy manner
   * You don't get the first set of buffered activities after connecting to a skill, which makes it appear like your conversation dies
   * In this artificial environment, where I am a user that happens to know what to say next to continue the dialog, I managed to get the dialog to go on, and was therefore able to see skills + streaming work in action, after the initial bug

**Comment by Zerryth** [comment]
Closing this issue, and opened #3008 specifically for ExpectReplies + Skills behavior
