### ISSUE TITLE
Adaptive Testing TestRunner refactor

### ISSUE THREAD

**Issue by joshgummersall** [microsoft/botbuilder-js#2959]
See https://github.com/microsoft/botbuilder-js/pull/2952 for more context.

**Comment by chon219** [comment]
The original adaptive testing package was implemented by me, can I this work item to make it fully on parity with the `TestUtils` in C#?

**Comment by chon219** [comment]
The goal to refactor TestRunner/TestUtils might be:
1. Make the `TestAdapter` configurable in `runTestScript`.
2. Move the initialization of `ResourceExplorer` to the outside, since event listener leak issue can be fixed in #2989 , it is okay for a collection of tests(e.g. action tests) to share one resource explorer instance.
3. Pass middlewares as parameters in `runTestScript`.

**Comment by joshgummersall** [comment]
@chon219 sure, please feel free to take over this issue and drive parity. My intention with the changes in #2952 was just to fix the emitter leak.

**Comment by chon219** [comment]
@joshgummersall @stevengum  I found that `TestUtils.RunTestSciprt` method in C# doesn't have `TestAdapter` parameter, and `TestUtils` itself dosen't have `TestAdapter` in constructor parameters. Is it OK to add this parameter in our JS implementation?
