### ISSUE TITLE
Use `releases/*` for release branches, Github actions, and Azure DevOps

### ISSUE THREAD

**Issue by joshgummersall** [microsoft/botbuilder-js#2967]
Currently, we use branch names like `4.11` to signify a release branch. We should use `releases/4.11` and leverage wildcards in our various CI configurations.

**Comment by stevengum** [comment]
This is a great idea, although I'm not sure about traction amongst the larger team. I think we might want to keep the latest stable version as `4.##` because it will appear at the top of the list, but for older versions we should definitely move towards a more easily sustainable configuration system. 

<sup>And/or start locking down pre-4.7 branches</sup>
