### ISSUE TITLE
LuisRecognizer.topIntent() cached ?

### ISSUE THREAD

**Issue by FKSI** [Microsoft/botbuilder-js#310]
Hi, 

I've been using the `LuisRecognizer` with Luis:

`let topIntent = LuisRecognizer.topIntent(res);`

I changed an intent name from `issue_airConditioner` to `issue.airConditioner` but LuisRecognizer is still returning the hold naming! Am I missing something?

PS: Yes I retrained and republished several times :)

**Comment by FKSI** [comment]
Ok, so after some digging. I found in `luisRecognizer.js` source the code the following method:

```
    normalizeName(name) {
        return name.replace(/\.| /g, "_");
    }
```

I'm wondering the rational behind that normalization 🤔?

**Comment by stevengum** [comment]
@chrimc62 or @stevenic can you chime in on the intent name normalization? 😄 

@FKSI I believe part of this is due to some additional tooling, i.e. [LUISGen](https://github.com/Microsoft/botbuilder-tools/tree/master/LUISGen).

@Kaiqb if we haven't yet done so, we should probably add some documentation explaining this name normalizing.

**Comment by FKSI** [comment]
Yes I bet, there is a good reason for that but clearly it has to be mentioned somewhere 😊 . I can do a PR if needed :)

**Comment by Stevenic** [comment]
@chrimc62 would need to comment on this bit of logic.

**Comment by sgellock** [comment]
this is by design and we will update our docs to enumerate where we don't support '.''s in names.
