### ISSUE TITLE
DialogContextError showing as multiple Trace entries in Application Insights

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-js#3673]
## Versions
4.13.1
Deployed Azure function bot from Composer

## Describe the bug
DialogContextError are split in app insights telemetry logs into multiple entries (see image below)

## To Reproduce
1. Create a Node Azure Functions bot (this is likely not an azure functions runtime issue though)
2. Add app insights
3. Add code or a dialog to throw a DialogContextError in the bot. 
4. Message the bot.
4. Look for Dialog context error in Telemetry (see image below)

## Screenshots
![image](https://user-images.githubusercontent.com/11055362/118004855-b307c400-b2fe-11eb-8f74-8fc383611e25.png)

**Comment by joshgummersall** [comment]
@EricDahlvang, `TRACE` events seem to correspond to individual lines of `stderr`, i.e. there will be entries for each line of a stack trace. Even a regular `console.error(new Error("stderr"))` yields the following in the transaction search log:
<img width="1119" alt="Screen Shot 2021-07-01 at 11 56 51 AM" src="https://user-images.githubusercontent.com/1235378/124176185-6cfbf080-da63-11eb-90b2-cb09c1c9e064.png">

That said, using `trackException` produces a more useful entry:
<img width="524" alt="Screen Shot 2021-07-01 at 11 58 11 AM" src="https://user-images.githubusercontent.com/1235378/124176325-9ddc2580-da63-11eb-8c3e-db110ea10888.png">

I don't think there's anything useful we can do here aside from possibly using the telemetry client to call `trackException` in the Bot Adapter `onTurnError` handler. What do you think?

**Comment by EricDahlvang** [comment]
That's odd.  This would at lest produce a single line in the log: `console.log(JSON.stringify(new Error("stderr")))`  `trackException` looks best though!

It looks like Application Insights is switching to #azure/log soon: https://github.com/microsoft/ApplicationInsights-node.js/pull/733 maybe this will help?

**Comment by sw-joelmut** [comment]
Hi @EricDahlvang and @joshgummersall
We tried to reproduce the issue without success, using both a Composer bot and a bot sample.
1. Using an Azure function Composer bot locally or deployed, the traces are not being registered in the Application Insights, but shown in BotFramework Emulator.
  ![image](https://user-images.githubusercontent.com/62260472/148120332-6e0f70b3-1c1a-4f13-9399-795a16f9c2af.png)
2. Using the [21.corebot-app-insights](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/21.corebot-app-insights) sample with a simple `console.error(new Error("stderr"))`, thrown when the `beginDialog` is executed and then captured by the `onTurnError` handler, the Application Insights showed a singular trace instead of multiple.
  ![image](https://user-images.githubusercontent.com/62260472/148120341-c5b15992-f78e-43b9-bb2c-6ad41e6f71e2.png)

Regarding Composer, is there any telemetry configuration we are missing?, causing the traces to not be properly shown in Application Insights?
Here is the configuration we used to connect to the Application Insights.
```json
"telemetry": {
  "logActivities": true,
  "logPersonalInformation": true,
  "options": {
    "connectionString": "InstrumentationKey=<INSTRUMENTATION_KEY>;IngestionEndpoint=https://westus-0.in.applicationinsights.azure.com/"
  }
}
```
