### ISSUE TITLE
Bot framework doesn't return plain JWT

### ISSUE THREAD

**Issue by nilsmehlhorn** [microsoft/botbuilder-js#3751]
## Versions
What package version of the SDK are you using: 4.12.0
What nodejs version are you using: 14
What browser version are you using: n/a
What os are you using: n/a

## Describe the bug

I'm building an app for Microsoft Teams which requires the user to sign-in inside a bot dialog or message extension. The overall sign-in process works fine. I'm retrieving the token via [`BotFrameworkAdapter.getUserToken()`](https://docs.microsoft.com/en-us/javascript/api/botbuilder/botframeworkadapter?view=botbuilder-ts-latest#getUserToken_TurnContext__string__string_) and if no token is available, the user will be prompted to login based on [`BotFrameworkAdapter.getSignInLink()`](https://docs.microsoft.com/en-us/javascript/api/botbuilder/botframeworkadapter?view=botbuilder-ts-latest#getSignInLink_TurnContext__string__CoreAppCredentials__string__string_).

Usually, the token is a JWT. This allows me to decode the claims and verify that it contains all scopes that are currently necessary to use the app. If I'm adding a Graph API permission in the future (e.g. for a new feature), I can therefore prompt the user to sign-in again so that the app doesn't break for users who are already signed in with lesser permissions.

Since recently, tokens are increasingly not issued as plain JWT. Rather, they look similar to an [example from the Graph API documentation](https://docs.microsoft.com/en-us/graph/auth/auth-concepts):

```
EwAoA8l6BAAU7p9QDpi/D7xJLwsTgCg3TskyTaQAAXu71AU9f4aS4rOK5xoO/SU5HZKSXtCsDe0Pj7uSc5Ug008qTI+a9M1tBeKoTs7tHzhJNSKgk7pm5e8d3oGWXX5shyOG3cKSqgfwuNDnmmPDNDivwmi9kmKqWIC9OQRf8InpYXH7NdUYNwN+jljffvNTewdZz42VPrvqoMH7hSxiG7A1h8leOv4F3Ek/oeJX6U8nnL9nJ5pHLVuPWD0aNnTPTJD8Y4oQTp5zLhDIIfaJCaGcQperULVF7K6yX8MhHxIBwek418rKIp11om0SWBXOYSGOM0rNNN59qNiKwLNK+MPUf7ObcRBN5I5vg8jB7IMoz66jrNmT2uiWCyI8MmYDZgAACPoaZ9REyqke+AE1/x1ZX0w7OamUexKF8YGZiw+cDpT/BP1GsONnwI4a8M7HsBtDgZPRd6/Hfqlq3HE2xLuhYX8bAc1MUr0gP9KuH6HDQNlIV4KaRZWxyRo1wmKHOF5G5wTHrtxg8tnXylMc1PKOtaXIU4JJZ1l4x/7FwhPmg9M86PBPWr5zwUj2CVXC7wWlL/6M89Mlh8yXESMO3AIuAmEMKjqauPrgi9hAdI2oqnLZWCRL9gcHBida1y0DTXQhcwMv1ORrk65VFHtVgYAegrxu3NDoJiDyVaPZxDwTYRGjPII3va8GALAMVy5xou2ikzRvJjW7Gm3XoaqJCTCExN4m5i/Dqc81Gr4uT7OaeypYTUjnwCh7aMhsOTDJehefzjXhlkn//2eik+NivKx/BTJBEdT6MR97Wh/ns/VcK7QTmbjwbU2cwLngT7Ylq+uzhx54R9JMaSLhnw+/nIrcVkG77Hi3neShKeZmnl5DC9PuwIbtNvVge3Q+V0ws2zsL3z7ndz4tTMYFdvR/XbrnbEErTDLWrV6Lc3JHQMs0bYUyTBg5dThwCiuZ1evaT6BlMMLuSCVxdBGzXTBcvGwihFzZbyNoX+52DS5x+RbIEvd6KWOpQ6Ni+1GAawHDdNUiQTQFXRxLSHfc9fh7hE4qcD7PqHGsykYj7A0XqHCjbKKgWSkcAg==
```

Although this looks like Base64-encoded data and it even says `jwt` above the snippet in the documentation, this is clearly not a plain JWT. Honestly, I'm not quite sure what it is, however, I assume it is a JWS or a JWT encoded with a nonce.

## To Reproduce

1. Login user via [`BotFrameworkAdapter.getSignInLink()`](https://docs.microsoft.com/en-us/javascript/api/botbuilder/botframeworkadapter?view=botbuilder-ts-latest#getSignInLink_TurnContext__string__CoreAppCredentials__string__string_)
2. Retrieve token via [`BotFrameworkAdapter.getUserToken()`](https://docs.microsoft.com/en-us/javascript/api/botbuilder/botframeworkadapter?view=botbuilder-ts-latest#getUserToken_TurnContext__string__string_)
3. See that token sometimes is not a plain JWT

## Expected behavior

I'm thinking that I should probably treat this token as opaque, however, because the sign-in (and sign-in link generation) is hidden behind the bot framework I don't see another opportunity for adding permissions to an already deployed application, i.a. verifying that an access token provides the required permissions. Since my app also acts on behalf of the user at a later point in time, it's also not viable to prompt for sign-in after I'm receiving a 403er response from the Graph API.

1. Is there a way to decode these kinds of tokens or instead make sure that my app will only receive decodable JWTs?
2. If not, is there an alternative for verifying access token permissions (scopes)?

## Screenshots
n/a

## Additional context

Full disclosure, I've already posted this to StackOverflow [here](https://stackoverflow.com/questions/67849620/bot-framework-doesnt-return-jwt), however, the answers over there weren't very helpful. So, you're of course free to close this right away, but I'd still love a hint and maybe this is even a bug in the token issuing as it only occurs sporadically.

**Comment by Zerryth** [comment]
@nilsmehlhorn you're correct in that typically you would want to treat the token as opaque to the OAuth client (in this case, the bot who'll act on behalf of the user)--though I do see what you mean though when you reference the scenario of scopes potentially changing that you would want to be able to check the token to see if the appropriate scopes were authorized in the token that the bot currently has.

> Since recently, tokens are increasingly not issued as plain JWT.
The fact that the tokens that are issued are sometimes not JWT is definitely news to me! 😮 
Are you able to pinpoint when exactly they are sent back in a non-JWT format?

It doesn't sound like this is necessarily an issue with the Bot Framework SDK itself, as the the Auth. Server is the one who creates the token itself (which I think you probably guessed at as well)...hmm...

I'll dig into this a little to verify if there can be anything done on the SDK's end. You might just have to do some custom business logic in your bot to handle catching 403s and try by default asking the user to sign in one more time, then retrying the request at Graph API again with new token.

**Comment by Zerryth** [comment]
Ok, so still haven't heard back regarding what you're doing to trigger the scenario of getting back a non-JWT token response, nor do you mention how you're setting up your Bot + Graph API + Auth. Server/Identity Provider, so I don't really have much in the way of being able to help you research possible solutions...

So I'll give these guidelines:

- If you want to check the token in a pre-check fashion (inspecting token in the Bot before calling the Graph API), you will need to dig into documentation or source code (if available) of the auth. server/identity provider that you're requesting a token from, so you could identify the structure of the token the bot is receiving and decode appropriately. I don't know your setup, therefore I couldn't do any precursor research to help in this regard...
- If you want follow canonical OAuth specs, you would keep the token opaque to the Bot (the OAuth Client).
   - I suggest then maybe on catching 403 errors and attempting 1-more retry of just prompting the user to sign in, in case of edge case of them having a token that does not have sufficient scopes to call particular Graph API request

___

Going to close this issue, as the Bot Framework GitHub repos are for filing bugs or feature requests. This does not appear to be a bug in the SDK itself, and rather a discrepancy in behavior introduced by whichever AS/Id.P you're calling for the token. I would advise that you provide more detail on your setup in stack overflow, so that way the community could better weigh in on potentially what format the non-JWT token is coming back to you in

**Comment by Zerryth** [comment]
Oh, of course I see your response after I responded myself 😅

And yes, I agree that it's strange that the supposed "JWT" in the Graph API documentation isn't actually a JWT, which is pretty confusing.
