### ISSUE TITLE
Bot Framework updating Teams activity with empty content

### ISSUE THREAD

**Issue by Fradantim** [microsoft/botbuilder-js#3822]
## Versions
What package version of the SDK are you using. 4.8.0
What nodejs version are you using 10.15.3
What browser version are you using Google Chrome
What os are you using Windows 

## Describe the bug
I am experimenting some strange behaviour between a bot and ms teams.

Basically the bot sends me an Adaptive Card and when I interact again the bot will update that last message holding that card with the text "I got updated!".

Inside ms teams (both windows desktop and web) the messages gets updated indicating "Updated" but with an empty content. This content is not filled until I change the chat and come back.

I can't tell if this is an expected behaviour or if I'm making some kind of mistake.

## To Reproduce
This is a simplified example of the code:
``` json
"dependencies": {
        "adaptivecards": "^2.1.0",
        "axios": "^0.21.0",
        "botbuilder": "~4.8.0",
        "dotenv": "^8.2.0",
        "restify": "~8.4.0",
        "(...)":"(...)"
}
``` 

``` js
const adapter = new BotFrameworkAdapter({...});

adapter.onTurnError = onTurnErrorHandler;

const myBot = new EchoBot();

static processActivity(req, res) {
    adapter.processActivity(req, res, async context => {
        // Route to main dialog.
        await myBot.run(context);
    });
    }
```

``` js
class EchoBot extends ActivityHandler {
    constructor() {
        super();

        this.onMessage(async (context) => {
            await doSomething(context);
        });
    }
}
```

``` js
someCardContent = {...};
lastCardId = undefinded;

async function doSomething(turnContext) {
    if (!lastCardId) {
        { lastCardId } = await turnContext.sendActivity(MessageFactory.attachment(CardFactory.adaptiveCard(someCardContent)));
    } else {
        const newActivity = MessageFactory.text('I got updated!');
        newActivity.id = lastCardId;
        lastCardId = undefinded;
        await turnContext.updateActivity(newActivity)
    }
}
```

Order as seen in Teams:

1 I interact with the bot (greeting it)

2 The bot sends me a card: Original message
![image](https://user-images.githubusercontent.com/5752124/123634700-299a4b80-d7f1-11eb-9cef-dcee588aa40e.png)

3a I interact again (pressing the button), the card gets updated ("Actualizado" = "Updated"):
Updated Message
![image](https://user-images.githubusercontent.com/5752124/123634717-2e5eff80-d7f1-11eb-8fd4-b973b62b3b0b.png)

3b In the left panel I can see the message's new content
![image](https://user-images.githubusercontent.com/5752124/123634860-58182680-d7f1-11eb-9507-b988421ead5b.png)

4 I switch conversations and come back to the bot's chat
Updated Message after conversation switch
![image](https://user-images.githubusercontent.com/5752124/123634748-361ea400-d7f1-11eb-8333-a8cee4c2db4a.png)

## Expected behavior
Get the updated message without the need to switch chats.

## Additional context
I'm not allowed to share the bot's manifest, it's for a comany domain.

**Comment by stevengum** [comment]
@clearab, who's the best contact person on the Teams team to look into this issue since it seems to deal with how the updated activity is rendered in the Teams clients?

**Comment by clearab** [comment]
@Wajeed-msft can you take a look at this one? I'm guessing it is the switching from a card to a text message that is messing with the refresh. If that is the case, closing this issue and creating one in your tracking system seems like the right approach.

@Fradantim Are you seeing the same behavior if you update the message with a new card, rather than text? Also, you could potentially take a look at the new aciton.execute action to update the card in-place (https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview).

**Comment by v-kydela** [comment]
Linking: https://stackoverflow.com/questions/68105315/bot-framework-updating-teams-activity-with-empty-content

**Comment by Fradantim** [comment]
@clearab Updating the card-message with a new card does work ok (just tested)

I will try those new action.execute as soon as I can.

**Comment by Fradantim** [comment]
@clearab 
i'm unable to change the adaptive card with this content
![imgage](https://docs.microsoft.com/en-us/microsoftteams/platform/assets/images/adaptive-cards/universal-action-model.png)

I tried setting "refresh" as an array and as a object with an "action" member. Both times I got an error while trying to send the message:

Trace:
 [onTurnError] unhandled error: Error: Payload is incorrect
    at BotFrameworkAdapter.onTurnErrorHandler [as turnError] (/opt/app-root/src/services/exceptions.js:21:17)
    at middleware.run.then (/opt/app-root/src/node_modules/botbuilder-core/lib/botAdapter.js:89:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by clearab** [comment]
The refresh section shouldn't be necessary, just changing the action type to action.execute, then responding to the incoming invoke. I think it is possible to respond to that invoke with text, rather than an adaptive card.

Doesn't change the core bug though, which is client refresh not getting triggered when updating an activity that contains an adaptive card to just a text message (which is purely a Teams client issue).

I'm going to go ahead and close this, but I'll continue to monitor the StackOverflow question to make sure the Teams group follows up. (I'm assuming this is a bug, so it may take a bit for a fix). In the interim, I'd definitely just replace the card with a new card if at all possible, rather than a text message.
