### ISSUE TITLE
Missing local information in TurnContext in onTeamsMembersAdded method 

### ISSUE THREAD

**Issue by MajaEffenberg** [microsoft/botbuilder-js#4042]
## Versions
What package version of the SDK are you using: `4.15.0`
What nodejs version are you using: `16.13.1`

## Describe the bug
In  [`onTeamsMembersAdded`](https://docs.microsoft.com/en-us/java/api/com.microsoft.bot.builder.teams.teamsactivityhandler.onteamsmembersadded?view=botbuilder-java) method in TeamsActivityHandler, parameter `context` which has a type `TurnContext` does not include property `context.activity.locale`. As a result,it is not possible to read the local information of a member joining the channel and display the welcome message to the user in the appropriate language.

## Expected behavior
After the user has joined the channel, the locale value is read from context.activity.local in the onTeamsMembersAdded method. Then the welcome message is displayed to the user in the appropriate language, depending on the locale value.

**Comment by tdurnford** [comment]
@EricDahlvang Do you have any idea what the appropriate behavior is here?

**Comment by EricDahlvang** [comment]
Teams is not currently sending locale with the ConversationUpdate when team members are added. Presumably since multiple members are added? However, it does appear Teams sends Locale with the installationUpdate event (thanks @clearab ). So, one workaround might be to cache the locale when the bot receives https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=json#install-update-event and use that locale to respond to onTeamsMembersAdded.

**Comment by carlosscastro** [comment]
Given that Eric documented well what is supported and how to work around this, closing this issue. If the workarounds do not work feel free to reopen. Thanks!
