### ISSUE TITLE
Adaptive Card invoke activity type fails when used with prompts

### ISSUE THREAD

**Issue by harshithkashyap** [microsoft/botbuilder-js#4119]
## Versions
What package version of the SDK are you using: 4.13.5
What nodejs version are you using: 14.9
What browser version are you using: NA
What os are you using: NA

## Describe the bug
When an adaptive card `invoke` activity type is sent by the client, the activity is ignored when the bot is waiting on a **prompt**. This is visible from the following lines of code at `continueDialog` - https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs/src/prompts/prompt.ts#L221-L223
![image](https://user-images.githubusercontent.com/4183260/154222047-1b7e9bfd-4298-4119-8a99-a95073acd51d.png)

## To Reproduce
1. Send an Adaptive Card with `Action.Execute` using any available prompts.
2. Submit the response from the client.
3. The activity sent by the client will pass through `continueDialog` of the prompt and skip the dialog.

## Expected behavior
The SDK should handle both `Message` and `Invoke` activity types.

**Comment by stevkan** [comment]
@harshithkashyap, I was able to repro this issue. Testing seems to indicate that the issue _may_ lie deeper in the code. I am working on getting this in front of the right person to handle. We'll post an update when we know more.

**Comment by stevkan** [comment]
@harshithkashyap, I got a little hung up on a partially related issue I was experiencing in my own bot and didn't recognize a key detail of your own. Namely, that you are trying to pass in an adaptive card into a prompt. This, by design, is not doable. As can be seen in the samples (ref: [07.using-adaptive-cards](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/07.using-adaptive-cards)) adaptive cards are sent as a regular activity.

This is a feature that has never been adopted. You do have the ability to build your own custom prompt if you are intent on sending an adaptive card thru one. In the botbuilder-community-dotnet repo, there is a [Cards](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Cards) library that was designed specifically to address this issue. You could use that as a jumping off point if you wanted to design an adaptive cards prompt for use in a JS Node bot.

**Comment by harshithkashyap** [comment]
@stevkan Here's a snippet from our existing codebase.
![image](https://user-images.githubusercontent.com/4183260/157684088-cad5b1d3-abe1-4722-a9d2-a8f36d00e673.png)

Prompts have always supported sending any `Activity` type instead of string.

![image](https://user-images.githubusercontent.com/4183260/157684414-5fca7c90-5e53-4c39-837f-1aac0b338776.png)

This issue is specifically related to handling `adaptiveCard/action` and `invoke` type activities. The prompt should be able to able to handle non-message activities.
