### ISSUE TITLE
The `Response` in Botbuilder is not compatiable with `Response` in Restify.

### ISSUE THREAD

**Issue by yukun-dong** [microsoft/botbuilder-js#4376]
## Versions
What package version of the SDK are you using. 4.18.0
What nodejs version are you using 14.19.0
What browser version are you using
What os are you using. win 11

## Describe the bug
(https://github.com/microsoft/botbuilder-js/blob/d55b5b99b37a49cf69fa005c744c7d0e367a82c5/libraries/botbuilder/src/interfaces/response.ts#L6)
When I write code as below, it shows error: the Restify Response is not assignable to BotBuilder Response, which is contradictory to the comments above.
<img width="935" alt="image" src="https://user-images.githubusercontent.com/25220706/203487894-4a7cee28-db0c-4bf9-b860-2e5c79a3d3d1.png">

## Expected behavior
These two should be compatiable.

**Comment by stevkan** [comment]
@yukun-dong - Unfortunately, I am unable to recreate this issue. I have tried with two different bot implementations and both work, as expected. I tested Restify with both version 8.5.1 and 9.0.0 using Node v4.19.3.

Can you tell me which version of Restify it is you are using? For that matter, could you just post your entire package.json?
What happens if you upgrade to Node 16 or Node 18?
Are you able to test on another machine or environment?

**Comment by yukun-dong** [comment]
> @yukun-dong - Unfortunately, I am unable to recreate this issue. I have tried with two different bot implementations and both work, as expected. I tested Restify with both version 8.5.1 and 9.0.0 using Node v4.19.3.
> 
> Can you tell me which version of Restify it is you are using? For that matter, could you just post your entire package.json? What happens if you upgrade to Node 16 or Node 18? Are you able to test on another machine or environment?

I used Restify 8.5.5. I created a repo here https://github.com/yukun-dong/botCloudAdapter. After cloning and running `npm install`,  you should see the error in index.ts.

**Comment by stevkan** [comment]
@yukun-dong, thank you for your patience. I had a credentials issue I had to work thru but has not been resolved.

I will take a look at your repo and let you know what I find.

**Comment by stevkan** [comment]
@yukun-dong, I resolved your issue by installing `@types/node` as a devDependency. I'm assuming it needs to match the version of Node being run, but not 100% on that. Regardless, I tried installing both version 16.11.6 and 18.11.9 (latest) and it ran without issue each time with the error disappearing.

As this should resolve the issue for you, as well, I am closing this. If the problem persists, please feel free to reopen issue.

**Comment by yukun-dong** [comment]
> @yukun-dong, I resolved your issue by installing `@types/node` as a devDependency. I'm assuming it needs to match the version of Node being run, but not 100% on that. Regardless, I tried installing both version 16.11.6 and 18.11.9 (latest) and it ran without issue each time with the error disappearing.
> 
> As this should resolve the issue for you, as well, I am closing this. If the problem persists, please feel free to reopen issue.

Thanks, it worked. But I am curious why the @types/node can solve this problem. Do you know the reason behind this?

**Comment by stevkan** [comment]
@yukun-dong - I'm only speculating at this as I'm not real strong http requests/responses. As is shown in the [link](https://github.com/microsoft/botbuilder-js/blob/d55b5b99b37a49cf69fa005c744c7d0e367a82c5/libraries/botbuilder/src/interfaces/response.ts#L5) you provided, the adapter:

> Represents a Node.js HTTP Response, including the minimal set of use properties and methods.
> Compatible with Restify, Express, and Node.js core http.

In a JS build, this would be enough. But since this is TS, it is checking types. Restify builds on the [response](https://github.com/restify/node-restify/blob/19b86627fb9122456aec6c1fb5d22e439e5080db/lib/response.js#L33) object which, effectively, changes its type:

> Patch Response object and extends with extra functionalities

I believe including `@types/node` simply aligns the two response objects so they are explicitly the same.

**Comment by yukun-dong** [comment]
> @yukun-dong - I'm only speculating at this as I'm not real strong http requests/responses. As is shown in the [link](https://github.com/microsoft/botbuilder-js/blob/d55b5b99b37a49cf69fa005c744c7d0e367a82c5/libraries/botbuilder/src/interfaces/response.ts#L5) you provided, the adapter:
> 
> > Represents a Node.js HTTP Response, including the minimal set of use properties and methods.
> > Compatible with Restify, Express, and Node.js core http.
> 
> In a JS build, this would be enough. But since this is TS, it is checking types. Restify builds on the [response](https://github.com/restify/node-restify/blob/19b86627fb9122456aec6c1fb5d22e439e5080db/lib/response.js#L33) object which, effectively, changes its type:
> 
> > Patch Response object and extends with extra functionalities
> 
> I believe including `@types/node` simply aligns the two response objects so they are explicitly the same.

I see, thanks for answering.
