### ISSUE TITLE
 Need reply functionality in bot builder 4.0 SDK for Teams

### ISSUE THREAD

**Issue by druveen** [microsoft/botbuilder-js#4410]
**Is your feature request related to a problem? Please describe.**

Today there is no way to send a message to a thread (reply) using bot builder 4.0 SDK

Scenario:-
1. User A -> Types a message in Teams App (bot)
2. Now Bot has to reply to the same thread that user A has started in Teams App (bot)

This is useful when the user has posted many messages in the bot and the bot replies to those messages later point in time... 
As currently, the bot's reply goes as a new message thus the user is not sure for which of his message reply has come.

<img width="1071" alt="Screenshot 2023-01-16 at 4 23 53 PM" src="https://user-images.githubusercontent.com/572266/213619944-11e3fa41-341d-4e70-818d-d524bd2f9fc9.png">

**Describe the solution you'd like**
I would like to have the below solution
<img width="1434" alt="Screenshot 2023-01-16 at 4 23 59 PM" src="https://user-images.githubusercontent.com/572266/213619954-ef973da7-b98c-4449-9895-7fbf204fe394.png">

**Describe alternatives you've considered**
No alternative is present 

**Additional context**
Using API https://smba.trafficmanager.net/apac/v3/conversations/{conversationsId}/activities/{activitieId} also send as new message

https://techcommunity.microsoft.com/t5/teams-developer/how-to-send-a-message-to-a-thread-reply-using-botbuilder-4-0-sdk/m-p/3716974

**Comment by JhontSouth** [comment]
Hi everyone,  

For this feature request we have tried several options to make the quoted reply, but none of them have been successful. 

First, we tested different parameters for the BotConnector's [ReplyToActivity](https://learn.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.conversationsextensions.replytoactivityasync?view=botbuilder-dotnet-3.0#Microsoft_Bot_Connector_ConversationsExtensions_ReplyToActivityAsync_Microsoft_Bot_Connector_IConversations_System_String_System_String_Microsoft_Bot_Connector_Activity_System_Threading_CancellationToken_&preserve-view=true) method (replyTo, recipientId), but it didn't change the current behavior, it sends a new message instead of a reply.   

Then, we found the [Graph API ReplyToMessage](https://learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&tabs=http) that allowed us to reply to messages, but it creates a thread instead of a quoted reply.

<html>
<body>
<div class="OutlineElement Ltr  BCX0 SCXO109811735" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left;"><span class="EOP SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 18px; font-family: Calibri, sans-serif; color: windowtext;"> </span></p></div><div class="OutlineElement Ltr SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left;"><span data-contrast="auto" class="TextRun SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: windowtext; background-color: transparent; font-weight: normal; font-style: normal; text-decoration: none; font-size: 11pt; font-family: Calibri, sans-serif; line-height: 18px;"><span class="NormalTextRun SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-color: inherit;">These are the results that we received testing the APIs in different conversation types.</span></span><span class="EOP SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 18px; font-family: Calibri, sans-serif; color: windowtext;"> </span></p></div><div class="OutlineElement Ltr SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TableContainer SCXO109811735 BCX0" style="margin: 2px 0px 2px -5px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; position: relative;"><div id="{7db6aa99-97f5-48d8-821e-873759198d56}{44}" class="WACAltTextDescribedBy SCXO109811735 BCX0" aria-hidden="true" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; position: absolute; visibility: hidden; z-index: -100;"></div>

API | Conversation type | Results
-- | -- | --
Azure bot service (ReplyToActivity) | Channel | It sends the message in a thread.
  | 1:1 | It sends a new message to the chat. No reply.
  | Meeting | It sends a new message to the chat. No reply.
Microsoft Graph (ReplyToMessage) | Channel | It sends the message in a thread.
  | 1:1 | It sends a new message to the chat. No reply.
  | Meeting | It sends a new message to the chat. No reply.

</div></div><div class="OutlineElement Ltr SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXO109811735 BCX0" xml:lang="ES-ES" lang="ES-ES" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left;"><span data-contrast="auto" class="TextRun SCXO109811735 BCX0" xml:lang="ES-ES" lang="ES-ES" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: windowtext; background-color: transparent; font-weight: normal; font-style: normal; text-decoration: none; font-size: 11pt; font-family: Calibri, sans-serif; line-height: 18px;"><span class="NormalTextRun SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-color: inherit;"></span></span><span class="EOP SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 18px; font-family: Calibri, sans-serif; color: windowtext;"> </span></p></div><div class="OutlineElement Ltr SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left;"><span data-contrast="auto" class="TextRun SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: windowtext; background-color: transparent; font-weight: normal; font-style: normal; text-decoration: none; font-size: 11pt; font-family: Calibri, sans-serif; line-height: 18px;"><span class="NormalTextRun SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-color: inherit;">We'll continue looking for other APIs that allow us to send a quoted reply as the issue requires.</span></span><span class="EOP SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 18px; font-family: Calibri, sans-serif; color: windowtext;"> </span></p></div><div class="OutlineElement Ltr SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left;"><span data-contrast="auto" class="TextRun SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: windowtext; background-color: transparent; font-weight: normal; font-style: normal; text-decoration: none; font-size: 11pt; font-family: Calibri, sans-serif; line-height: 18px;"><span class="NormalTextRun SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-color: inherit;">Please, let us know if you have any information that can help us.</span></span><span class="EOP SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 18px; font-family: Calibri, sans-serif; color: windowtext;"> </span></p></div><div class="OutlineElement Ltr SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left;"><span data-contrast="auto" class="TextRun SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: windowtext; background-color: transparent; font-weight: normal; font-style: normal; text-decoration: none; font-size: 11pt; font-family: Calibri, sans-serif; line-height: 18px;"><span class="NormalTextRun SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-color: inherit;"></span></span><span class="EOP SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 18px; font-family: Calibri, sans-serif; color: windowtext;"> </span></p></div><div class="OutlineElement Ltr  BCX0 SCXO109811735" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left;"><span data-contrast="auto" class="TextRun SCXO109811735 BCX0" xml:lang="EN-US" lang="EN-US" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: windowtext; background-color: transparent; font-weight: normal; font-style: normal; text-decoration: none; font-size: 11pt; font-family: Calibri, sans-serif; line-height: 18px;"><span class="NormalTextRun SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-color: inherit;">Thanks,</span></span><span class="EOP SCXO109811735 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 18px; font-family: Calibri, sans-serif; color: windowtext;"> </span></p></div>
</body>
</html>

**Comment by JhontSouth** [comment]
Hi everyone,  

For this feature request we have tried several options to make the quoted reply, but none of them have been successful. 

First, we tested different parameters for the BotConnector's [ReplyToActivity](https://learn.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.conversationsextensions.replytoactivityasync?view=botbuilder-dotnet-3.0#Microsoft_Bot_Connector_ConversationsExtensions_ReplyToActivityAsync_Microsoft_Bot_Connector_IConversations_System_String_System_String_Microsoft_Bot_Connector_Activity_System_Threading_CancellationToken_&preserve-view=true) method (replyTo, recipientId), but it didn't change the current behavior, it sends a new message instead of a reply.   

Then, we found the [Graph API ReplyToMessage](https://learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&tabs=http) that allowed us to reply to messages, but it works only in Channels and it creates a thread instead of a quoted reply. 

 
These are the results that we received testing the APIs in different conversation types.

<html>
<body>


API | Conversation type | Results
-- | -- | --
[Azure bot service](https://learn.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.conversationsextensions.replytoactivityasync?view=botbuilder-dotnet-3.0#Microsoft_Bot_Connector_ConversationsExtensions_ReplyToActivityAsync_Microsoft_Bot_Connector_IConversations_System_String_System_String_Microsoft_Bot_Connector_Activity_System_Threading_CancellationToken_&preserve-view=true) (ReplyToActivity) | Channel | It sends the message in a thread.
  | 1:1 | It sends a new message to the chat. No reply.
  | Meeting | It sends a new message to the chat. No reply.
[Microsoft Graph](https://learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&tabs=http) (ReplyToMessage) | Channel | It sends the message in a thread.
  | 1:1 | It doesn't work in 1:1 conversations.
  | Meeting | It doesn't work in meeting conversations.


</body>
</html>

We'll continue looking for other APIs that allow us to send a quoted reply as the issue requires. 

Please, let us know if you have any information that can help us. 

Thanks.

**Comment by JhontSouth** [comment]
We tried different alternatives to perform the quoted reply action, but we haven't found a solution using an API since this functionality is not currently available for bots. However, we found these alternatives: 

- Reply to a message in a thread. This [sample](https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-bot-initiate-thread-in-channel-csharp/) can be used as example (it works for channels only). 

- A possible workaround could be adding in the reply the text of the original message with a preceding ">" character. This way, we can simulate a quoted reply.

![image](https://user-images.githubusercontent.com/122501764/232063528-ed5138fe-10c0-4aad-aa16-98afe2ab6395.png)

**Comment by JhontSouth** [comment]
Hi @druveen 
We tried different alternatives to perform the quoted reply action, but we haven't found a solution using an API since this functionality is not currently available for bots. However, we found these alternatives: 

Reply to a message in a thread. This [sample](https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-bot-initiate-thread-in-channel-csharp/) can be used as example (it works for channels only). 

A possible workaround could be adding in the reply the text of the original message with a preceding ">" character. This way, we can simulate a quoted reply.

![image](https://user-images.githubusercontent.com/122501764/232505055-d509dc04-ff97-43e9-82ee-f6c087003cf0.png)

**Comment by ubyontestproject** [comment]
@JhontSouth 

Thank you for looking into it... and giving detailed info.  I was mainly looking into a reply functionality in the bot/app chat window. The reply functionality was working for me in channels. 

Thank you 
Druveen Gangadhar

**Comment by ceciliaavila** [comment]
Hi @tracyboehrer, we think this issue can be closed. The requested Teams functionality is not yet available for bots to implement.

**Comment by Meligy** [comment]
Came here looking for the same functionality (ability to native reply to a message in 1:1 conversations), so, giving it a nudge.

**Comment by tracyboehrer** [comment]
This issue should be raised with Teams.  Closing since I don't have a way to transfer it.
