### ISSUE TITLE
GHSA-cf4h-3jhx-xvhq / CVE-2021-23358

### ISSUE THREAD

**Issue by mogadanez** [microsoft/botbuilder-js#4444]
## Versions
What package version of the SDK are you using.
 "botbuilder": "^4.19.2",

What nodejs version are you using
18.15.0

## Describe the bug
got   security   issue  https://github.com/advisories/GHSA-cf4h-3jhx-xvhq
yarn why underscore gives:
```
=> Found "adal-node#underscore@1.7.0"
info This module exists because "botbuilder#botframework-connector#adal-node" depends on it.

```

adal-node have underscore dependency as `"underscore": ">= 1.3.1"` but  1.7.0  installed instead of latest 1.13.6

**Comment by JhontSouth** [comment]
Hi @mogadanez, could you give us more details about the environment in which you got this bug?
We tested using the mentioned versions of _node_ and _botbuilder_ and, in all cases, the installed version of _underscore_ was 1.13.1, so we had no vulnerability issues.
In this [PR](https://github.com/microsoft/botbuilder-js/pull/4076), the version of _underscore_ was forced to 1.13.1, due to vulnerability issues.

**Comment by ceciliaavila** [comment]
Hi @tracyboehrer, we think this issue can be closed. We couldn't reproduce the error.
