### ISSUE TITLE
Vulnerable recognizers-text-suite is still in use in botbuilder-dialogs

### ISSUE THREAD

**Issue by guy-microsoft** [microsoft/botbuilder-js#4555]
botbuilder-dialogs v4.21.0 uses "@microsoft/recognizers-text-suite": "1.1.4" which has a security vulnerability. This is an old vulnerability and should be fixed as soon as possible.
The vulnerable package is lodash.trimend v4.5.1

**Comment by tracyboehrer** [comment]
Not exactly true.  Dialog does use an older version of recognizers-text because the newer version is a breaking change.  We use resolutions in in the SDK build to resolve to a new version of the offending package.  The problem originates in recognizers-text-number and should be mapped to 1.3.1.

We did this in the SDK build which clears the error on our scans.  But it's entirely possible that a bot would need to add this to it's resolutions in package.json.
