### ISSUE TITLE
replyToId not part of token response of oauthprompt

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/botbuilder-js#4595]
## Versions
```
   "botbuilder": "^4.21.0",
   "botbuilder-dialogs": "^4.21.0",
```
## Describe the bug
I implemented this [sample ](https://github.com/Microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/18.bot-authentication) in my NodeJS bot. The authentication works is expected. To optimize the userexperience I would like to replace the login button with something else or delete it. Just to show the user he was succesful in his task and make sure he or she does not click the button again (resulting in a confusing error message)

TO be able to do that, I need a replyToId and update or delete the card. For instance like this:

`await context.deleteActivity(context.activity.replyToId);`

or 

```
const finalCard = CardFactory.adaptiveCard(FinalCard);
finalCard.id = context.activity.replyToId;
const finalMsg = MessageFactory.attachment(finalCard);
finalMsg.id = context.activity.replyToId;
await context.updateActivity(finalMsg);
```

## To Reproduce
Install the sample I mentioned
After         if (tokenResponse) {In maindialog.js add  
`console.log(JSON.stringify(stepContext.context.activity));
`
You will notice that there is not repyToId field under activity

## Expected behavior
A replyToActivity value to use

**Comment by rampaged** [comment]
@HesselWellema,

Which channel are you using?

"[A2092](https://github.com/microsoft/botframework-sdk/blob/1171620db9f2b96eedb0cd16156e50689aa76408/specs/botframework-activity/botframework-activity.md?plain=1#L260)" mentions to allow bots to leave out `replyToId` for messages if the channel (ex: WebChat or DirectLine) doesn't use it.

https://github.com/microsoft/botbuilder-js/blob/8a3076884bdc688a0cb6dca706ce47d8106b9af0/libraries/botbuilder-core/src/turnContext.ts#L125-L134

**Comment by HesselWellema** [comment]
Using Directline.

**Comment by HesselWellema** [comment]
I see what you mean. Thanks for taking time. I will post on SO and ask for alternative ways to get what I need. Will probably  have to solve it in the web-chat code. @Stevkan always has good ideas in matters like these

**Comment by stevkan** [comment]
@HesselWellema - Checked SO and didn't see a post from you (that I noticed) so thought I'd just respond to you here since the conversation is already going and I have a potential answer.

So, it looks like, from your comment above, that the client you are using is Web Chat. That is actually to your benefit in this situation. The OAuth prompt that is rendered in Web Chat uses (or is transformed into) an adaptive card. Because of this, you can use the method demonstrated in the [05.custom-components/l.disable-adaptive-cards](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/05.custom-components/l.disable-adaptive-cards) sample of the BotFramework-WebChat repo to disable previously clicked on adaptive cards!

You'll notice that there isn't a readme.md file like in the other samples (there really should be), but the code is pretty self-explanatory. To be clear, out-of-the-box this code will disable all previously rendered and clicked on adaptive cards. If you don't mind the digital elbow grease, you could probably further isolate the OAuth prompt. But I'll leave that up to you.

![disableOAuthPromptACButton](https://github.com/microsoft/botbuilder-js/assets/18403946/2edd3ff0-e63f-4454-afef-e416dec56c1b)

Another option, albeit a less practical one, is you could update the text of the card. This could be done in conjunction with the first option or by itself. This wouldn't be relying on `updateActivity` or `deleteActivity` but instead monitoring for the OAuth prompt's containing activity as it is received by Web Chat. When the activity is received, but not fully rendered yet, we do a quick update to the adaptive card's button's text. This method does work and is sometimes necessary, but it's not perfectly clean and it also relies on making changes directly in the UI which isn't a best practice. Additionally, as the underlying code of Web Chat is subject to change in future releases, it could pose a breaking change in your deployment if some relied upon class, etc., in the rendered HTML should change.

Again, this is doable, but the first option is the better option. I implemented this for testing purposes a couple years ago in an instance of Web Chat I still use and I _think_ I had to update the path to the button's text once when an update changed some of the parent element's class names. It's also worth noting that if the page hosting Web Chat is refreshed or reloaded and you are persisting the conversation, the updated text will be lost as it was in response to an activity previously received.

If this second option is of interest, let me know and I can demonstrate how to do this. It's also entirely possible I already demonstrated this on SO in response to someone's posted question, so you may want to check there, first.

**Comment by HesselWellema** [comment]
Tx for reachting out @stevkan. Appreciate it.
 Actually I did find this sample and made a first attempt today to implement it. Was just trying to figure out a way to get these:
 Components: {
            AdaptiveCardContent,
            AnimationCardContent,
            AudioCardContent,
            HeroCardContent,
            OAuthCardContent,
            ReceiptCardContent,
            SignInCardContent,
            ThumbnailCardContent,
            VideoCardContent
          },
      
          In my react web-chat project. Not sure how to import or require them.
          
     The other parts seam pretty straightforward

**Comment by stevkan** [comment]
@HesselWellema - Let take a peek at my test react web chat project and I'll get back to you shortly.

**Comment by stevkan** [comment]
@HesselWellema - You should be able to import `Components` like below. From there, deconstruct the `Components` object to access the individual component objects:

```
import ReactWebChat, { Components } from 'botframework-webchat';
const { AdaptiveCardContent, AnimationCardContent, etc., etc.} from Components;
```

Hope of help!

**Comment by HesselWellema** [comment]
tx. I ended up doint it like this:
import ReactWebChat, { Components, createDirectLine } from 'botframework-webchat';
const OAuthCardContent = Components.OAuthCardContent;

I can now do with the oAuth card whatever I want. Great.

However: After authentication, webchat gives a console warning: queueIncomingActivitySaga.js:73 botframework-webchat: Timed out while waiting for activity "4ff2fa83-0b93-4d24-8bc1-4553aeff9a53" which activity "DHbNq7XfNhmAlnAaT5n2wj-eu|0000003" is replying to. 
The warning is allways on the first activity send from the bot to the webchat after authentication succeeds.
I will try and reproduce with a minimal set of samples (to eliminate the option that it relates to my own code) and create a bugreport.

**Comment by HesselWellema** [comment]
Cycling back to you @rampaged. According to the webchat team, they need the replytoId for the oAuthcard implemtation. As a result of the missing id, there is a wait for approx 4 seconds and an error in the console. This problem is reproducable with sample bot. It this something you guys can address?

**Comment by HesselWellema** [comment]
@stevkan , tx for cycling back. I spent a lot of time trying to solve this and eventually moved away from authentication via the oAuth prompt. Decided to implement authentication outside the webchat. In hindsight, a better approach for this usecase.
