### ISSUE TITLE
CertificateAppCredentials defaults tenant to botframework.com

### ISSUE THREAD

**Issue by XVincentX** [microsoft/botbuilder-js#4636]
https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-connector/src/auth/certificateAppCredentials.ts#L39
 
The `CertificateAppCredential` class does not require a tenant id when creating a new instance; yet I found out (and make me lose hours) is that if you are not providing it, it will automatically set it to `botframework.com` - which does not look like a good default

![image](https://github.com/microsoft/botbuilder-js/assets/1416224/49322cd2-4d96-4df5-8429-43eacd6cd499)

I am not too sure why such parameter is optional, since the authentication just cannot happen without a tenant ID, and using `botframework.com` as default does not look a good backup plan

https://github.com/microsoft/botbuilder-js/blob/f487de2b27c5ff62b0eb17388ba167cda7de1efb/libraries/botframework-connector/src/auth/authenticationConstants.ts#L31

**Comment by sw-joelmut** [comment]
Hi @XVincentX,

The [CertificateAppCredential](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-connector/src/auth/certificateAppCredentials.ts#L17) class has the `tenantId` parameter marked as optional and defaults to `botframework.com` because of MultiTenant apps.
BotBuilder supports multiple types of apps to authenticate, MultiTenant, SingleTenant and UserAssignedMSI ([more info](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=multitenant%2Caadv2%2Cjavascript#bot-identity-information)). Thus, by providing a `tenantId` for MultiTenant apps other than the default, the authentication will not work.
Additionally, the default value is also required for MultiTenant, and changing it will break MultiTenant authentication.

**Comment by tracyboehrer** [comment]
Since any change would be breaking, lets add comments around this behavior in that class.  There is probably a bit more history here since the other app types were added later.

**Comment by tracyboehrer** [comment]
"botframework.com" has been the default tenant in AppCredentials, however subclasses can change this.  As in the case of Gov cloud where its "MicrosoftServices.onmicrosoft.us".  Though the option is there to specify a different tenant in the constructor.

Most of this dates back far, when there was only MultiTenant auth.  It would appear that it just wouldn't be possible to change without creating a breaking change.  There probably is a clearer way if we were green rooming it.

Also, the credential factories, which is central to CloudAdapter have tenantId as optional too.  For example, CertificateServiceClientCredentialsFactory.
