### ISSUE TITLE
botConfig could not read kanji

### ISSUE THREAD

**Issue by NoDirective** [Microsoft/botbuilder-js#562]
## Versions
What package version of the SDK are you using.
BOT FRAMWORK V4
What nodejs version are you using
6.4.1
What browser version are you using
What os are you using

## Describe the bug
Give a clear and concise description of what the bug is.
In .bot file , I added my multi qna  maker configures. 
I set the name of qna using chinese  characters.  Because  I wanted to show them.
When I got the qna config using BotConfiguration.loadSync ,
it seemed  the chinese characters did not show correctly

[bug]

**Comment by sgellock** [comment]
please write a test and propose a fix for review

**Comment by v-kydela** [comment]
@cleemullins - Working on it

**Comment by v-kydela** [comment]
@NoDirective - May I ask what you mean when you say the characters did not show correctly? How are you displaying them?

According to my tests, `BotConfiguration.loadSync` is able to read Chinese characters from the bot file correctly. I tested by including an extra value in the Luis configuration:

    {
      "appId": "0711b769-c5f0-4688-8c99-067ac5a2c114",
      "authoringKey": "1D6dLhx0MYK2H4W8YNyORg==!cdcz+Ss0uh2wcVC7KJc+T707zZpgNtjieDn2KG/LI3G+6ykFp7IWftD7mTgB0/CV",
      "version": "0.1",
      "region": "westus",
      "type": "luis",
      "name": "BasicBotLuisApplication",
      "id": "6",
      "data": "中文鍵盤"
    }

中 is character 20013, and after reading the bot file with `BotConfiguration.loadSync` I was able to verify that the value read is indeed character 20013 using `console.log("Luis config:", luisConfig.data.charCodeAt(0), luisConfig.data);`

It also appears the emulator has no problem displaying Chinese characters retrieved from the bot file (I had changed the Luis configuration's name):

![chinese emulator](https://user-images.githubusercontent.com/41968495/47591104-4c2e8500-d923-11e8-894f-5fa17e96700b.jpg)

Since the characters are being read correctly, I don't think this is a bug in the SDK. But I would appreciate it if you could give me some more information about your issue.

**Comment by v-kydela** [comment]
@NoDirective - May I ask what you mean when you say the characters did not show correctly? How are you displaying them?

According to my tests, `BotConfiguration.loadSync` is able to read Chinese characters from the bot file correctly. I tested by including an extra value in the Luis configuration:

    {
      "appId": "07****14",
      "authoringKey": "1D****CV",
      "version": "0.1",
      "region": "westus",
      "type": "luis",
      "name": "BasicBotLuisApplication",
      "id": "6",
      "data": "中文鍵盤"
    }

中 is character 20013, and after reading the bot file with `BotConfiguration.loadSync` I was able to verify that the value read is indeed character 20013 using `console.log("Luis config:", luisConfig.data.charCodeAt(0), luisConfig.data);`

It also appears the emulator has no problem displaying Chinese characters retrieved from the bot file (I had changed the Luis configuration's name):

![chinese emulator](https://user-images.githubusercontent.com/41968495/47591104-4c2e8500-d923-11e8-894f-5fa17e96700b.jpg)

Since the characters are being read correctly, I don't think this is a bug in the SDK. But I would appreciate it if you could give me some more information about your issue.

**Comment by NoDirective** [comment]
> @NoDirective - May I ask what you mean when you say the characters did not show correctly? How are you displaying them?
> 
> According to my tests, `BotConfiguration.loadSync` is able to read Chinese characters from the bot file correctly. I tested by including an extra value in the Luis configuration:
> 
> ```
> {
>   "appId": "07****14",
>   "authoringKey": "1D****CV",
>   "version": "0.1",
>   "region": "westus",
>   "type": "luis",
>   "name": "BasicBotLuisApplication",
>   "id": "6",
>   "data": "中文鍵盤"
> }
> ```
> 中 is character 20013, and after reading the bot file with `BotConfiguration.loadSync` I was able to verify that the value read is indeed character 20013 using `console.log("Luis config:", luisConfig.data.charCodeAt(0), luisConfig.data);`
> 
> It also appears the emulator has no problem displaying Chinese characters retrieved from the bot file (I had changed the Luis configuration's name):
> 
> ![chinese emulator](https://user-images.githubusercontent.com/41968495/47591104-4c2e8500-d923-11e8-894f-5fa17e96700b.jpg)
> 
> Since the characters are being read correctly, I don't think this is a bug in the SDK. But I would appreciate it if you could give me some more information about your issue.

@v-kydela  Thank you for your reply.

I do not know if I did a get why to get name's value like below

```
 "name": "echobot-with-counter",
    "services": [
        {
            "type": "endpoint",
            "name": "development",
            "endpoint": "http://localhost:3978/api/messages",
            "appId": "",
            "appPassword": "",
            "id": "1"
        },
        {
            "type": "qna",
            "name": "漢字",
            "subscriptionKey": "abc",
            "kbId": "abc",
            "id":"qna1",
            "hostname":"https://myqna.azurewebsites.net",
            "endpointKey":"key"
        }
    ],
```

Then just  get qna1 like below 
const qnaConfig = botConfig.findServiceByNameOrId('qna1');
console.log(qnaConfig.name);

Here is the result of qnaConfig.name

**Comment by v-kydela** [comment]
@NoDirective - I need more information. Please tell me what application you are trying to get to display Chinese characters. Whether or not Chinese characters can display correctly has everything to do with fonts and character encoding.

`console.log` will write text to whatever is defined as the console. In my case I'm running my code from the Windows command prompt and so `console.log` writes to the command prompt. I do not expect the command prompt to be able to display Chinese characters correctly and it doesn't. The problem you're experiencing surely has to do with your method of output rather than the Bot Framework. That's why I made sure to output the character code to make sure the characters are being read correctly. Try outputting `qnaConfig.name.charCodeAt(0)`. It should be 28450.

**Comment by v-kydela** [comment]
@NoDirective - That's very curious because I can read 日本語 from a bot file and display it in the emulator just fine. I wonder if it has to do with the fonts installed on your system, or if it's an ASCII vs Unicode issue.

There are a few troubleshooting steps I'd like you to do. Go ahead and paste 日本語 into the emulator as the user to see if the emulator can render the characters at all. Also, try to determine what characters are actually getting stored in this.qnaconfig.name. You can do this by inspecting the value while debugging, or by having the bot display its length and character codes. Also try testing the bot in other channels.

If you can determine that your code is reading the characters correctly and that the issue only occurs in the emulator, this should be opened as an issue in the emulator repo.

**Comment by v-kydela** [comment]
@NoDirective - If you're actually using version 6.4.1 of Node, you should definitely try updating to the latest version. However, I suspect that's actually your version of npm and not Node. Please let me know what your Node version is with the command `node -v`

**Comment by NoDirective** [comment]
@v-kydela 
Thank you for help.
I have resolved  ut

**Comment by v-kydela** [comment]
@NoDirective - That's great! Could you let us know what the resolution was?

**Comment by NoDirective** [comment]
@v-kydela 
I am sorry  to reply late. Actually I also do not know the reason. It just seems do well if I add more string

**Comment by v-kydela** [comment]
I'm glad to hear this was resolved for you
