### ISSUE TITLE
Botframework-connector conversations missing members object id

### ISSUE THREAD

**Issue by avegys** [Microsoft/botbuilder-js#618]
## Versions
botframework-connector 4.1.5

## Describe the bug
9 days ago the function getActivityMembersWithHttpOperationResponse was removed from the botframework-connector conversations.ts and only function getActivityMembers was left. 

(node:4568) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: connectorClient.conversations.getConversationMembersWithHttpOperationResponse is not a function

Now there is no way to get member objectId which is returned by conversations API. 
getActivityMembers only returns JSON with member id and member name.

How should I get member object id now?

**Comment by sgellock** [comment]
This SDK is built using swagger generated clients around the ms-rest-js package.  The property you are talking about is not part of the Activity protocol, so I suspect that you are looking for an unpublished property of the raw payload.

The ms-rest-js library was changed so that the response is a polymorphic response that includes both the shape of the data as specified in the swagger file (in this case an array of channelAccount objects) as well as a property which represents the raw HTTP response, accessible off of a "_response" property.

_response.bodyText has the raw response of the request and
_response.parsedBody has the channelAccount[]
