### ISSUE TITLE
Proposal: Add new interface which extends storage interface with query() and count() methods

### ISSUE THREAD

**Issue by Ceridan** [Microsoft/botbuilder-js#729]
[Storage](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/storage.ts) interface with `write`, `read` and `delete` methods is enough for work with conversation state or user state, but when you need to get some statistics about your users - it is useless. 
I use [CosmosDbStorage](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-azure/src/cosmosDbStorage.ts) and store the UserState for every user. If I need to get some statistics, for example, how many users I have or to find all users with specific property value in UserState - I can't do it with my CosmosDbStorage in efficient way.
So, what I want is to add new interface, let call it `QueryableStorage` which extends storage with two new methods:
```
interface QueryableStorage extends Storage {
  query(querySpec: QuerySpec): Promise<StoreItems>;
  count(querySpec: QuerySpec): Promise<number>;
}

interface QuerySpec {
  query: string;
  parameters: {
      name: string;
      value: string;
  }[];
}
```
- `query` method will be useful when you need to find some data with a specific selection rule;
- `count` method is useful for any statistic queries which usually returns a number;

Of course, I also want to fix implementations like CosmosDbStorage.
What do you think?

**Comment by mdrichardson** [comment]
How do you foresee getting user stats? The issue I see with this is that if this resides in the bot code, any user communicating with the bot would be able to use the `query` and `count` methods. Be aware that if any user can query and count, it may raise privacy issues, depending what data you store. If this is your use case, please [open a new issue in the BotBuilder repo](https://github.com/Microsoft/BotBuilder/issues/new/choose), as that's the one that's used for Design Change Requests. I'm working on updating `CosmosDbStorage`, so I'll likely monitor the issue if you submit it.

If not, and you see this as more of an admin tool, it's likely something you'd need to implement yourself, since it wouldn't be used within the bot, itself. The [`@azure/cosmos`](https://docs.microsoft.com/en-us/javascript/api/@azure/cosmos/?view=azure-node-latest) npm package may help you get started.

**Comment by sgellock** [comment]
Thank you for the suggestion.  We're not going to implement this.
