### ISSUE TITLE
LuisRecognizer should include 'value', 'start', and 'end' properties for datetimeV2 resolutions

### ISSUE THREAD

**Issue by ctstone** [microsoft/botbuilder-js#846]
## Versions
What package version of the SDK are you using. `4.3.4`
What nodejs version are you using `10.14.1`
What browser version are you using `n/a`
What os are you using `Windows` `macOS`

## Describe the bug
A LUIS datetimeV2 entity includes extra information about the resolved date(s), including `start` and `end` for ranges, and `value` for single non-ranges.

`LuisRecognizer` only [returns](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/luisRecognizer.ts#L525) the `type` and `timex` properties which are not enough to reconstruct a `Date` object.

## To Reproduce
1. Add datetimeV2 builtin entity to your LUIS app
2. Query for "tomorrow" or "this morning"
3. Observe `start`, `end`, `value` properties in the raw API response (these are parsable date strings like `2019-04-03 08:00:00`)
4. Attempt to use those properties in a bot. The only thing that comes close is the `timex` property, `2019-04-03TMO`, which is not parsable by `Date` or `moment`.

## Expected behavior
LuisRecognizer entities should include the `start` `end` `value` properties from the resolved datetimeV2 entity

## Additional context
As a workaround, I can "redetect" the date entity locally using `recognizeDateTime` from `@microsoft/recognizers-text-date-time` but that defeats the purpose of using LUIS to centrally manage and detect my entities.

In theory I could probably re-resolve the value from the timex property using `TimexProperty` class from `@microsoft/recognizers-text-data-types-timex-expression` but that package lacks type definitions, and seems to not include the value resolution implementation in the shipped package, per [this bug](https://github.com/Microsoft/Recognizers-Text/issues/974) opened by the Bot Framework team last year.

[bug]

**Comment by dividor** [comment]
I agree 100%, this has been a huge pain for us on SDK4. I appreciate there is a move towards using timex, but as @ctstone mentions, the MS package for resolving these dates is broken and even with it we have to do additional work to re-parse things, when the LUIS REST API returns a perfectly reasonable structure. 

I think SDK 4.0 is a great step forward, but this single issue has resulted in a very difficult migration for us date handling from LUIS isn't working in a usable way.

**Comment by dividor** [comment]
@ctstone I found this workaround,

```
var Recognizers = require('@microsoft/recognizers-text-suite');
var entities = Recognizers.recognizeDateTime(text, Recognizers.Culture.English);
```

This returns a structure similar to what we saw in the LUIS recognizer for SDK 3, with start and end dates where possible. I am calling this which means existing code I have can be re-used.

Bot builder folks, given the formal MS recognizer returns the fields we need, should the node LuisRecognizer do the same perhaps?

**Comment by cahann** [comment]
@chrimc62

**Comment by johnataylor** [comment]
There is a property on the RecognizerResult called "luisResult". This is available in both JavaScript and C#, however the model is slightly different because the C# has a Properties dictionary on the RecognizerResult. This property gives you direct access to the data returned from LUIS.

The bug referred to regarding the resolution in the timex-expression library will be fixed in the next release of the node packages. The timex-expression library actually supports two types of resolution, the first simply uses the TIMEX value to mimic the examples resolutions you get in the response from LUIS. The second, more ambitious resolution allows you to provide constraints on a TIMEX expression such that it can be reduced to a datetime value. The constraints are themselves TIMEX expressions. Longer term this model seems very promising.
