### ISSUE TITLE
listTranscripts( ) throws error when accessing AzureBlobTranscriptStore

### ISSUE THREAD

**Issue by DanDev33** [Microsoft/botbuilder-js#853]
## Versions
botbuilder 4.3.4
botbuilder-azure 4.3.4 or 4.4.0-preview.56

## Describe the bug
After saving transcripts to AzureBlobTranscriptStore, calling
await myTranscriptStore.listTranscripts("emulator", pagedResult.continuationToken); fails
(see code below)

## To Reproduce
The following code snippit run using JS EchoBot fails:

// This function stores user transcript. Second part tries to list all stored transcripts.
async function logMyTranscripts(myTranscriptStore, turnContext) {

    try {
        // This works fine using botbuilder-azure 4.4.0-preview.56
        await myTranscriptStore.logActivity(turnContext.activity);
        turnContext.sendActivity(`transcript stored.`);
    } catch (err) {
        turnContext.sendActivity(`Write failed: ${err}`);
    }
    
    debugger;
    // Tried many differing approaches to get continuationToken to work in JS.
    // Constructor: async listTranscripts(channelId, continuationToken) {...}
    let pagedResult = await myTranscriptStore.listTranscripts("emulator", pagedResult.continuationToken);
    if (continuationToken.nextPartitionKey != null) { 
       debugger;
       // I cut out the processing code that was here until I can get the listTranscripts call to work.
   }
}

## Expected behavior
List of stored transcripts returned from storage.
Instead
AzureBlobTranscriptStore['checkedCollectionsKey'] resolves to undefined, and AzureBlobTranscriptStore['checkedCollectionsKey'][key] generates an error.

## Additional context
zipped project containing test code attached

[EchoBotJS-transcript-bug.zip](https://github.com/Microsoft/botbuilder-js/files/3041098/EchoBotJS-transcript-bug.zip)

[bug]

**Comment by cleemullins** [comment]
@DanDev33 Dan, from the text of this issue, it seems like something we've already fixed in the 4.4 cycle (to ship towards the end of this month). The bug(s) in question were cleaned up in PR #836 with [this commit](https://github.com/Microsoft/botbuilder-js/commit/b82a4c354672ea6ecbf4a564bb9d43f8211421ef#diff-aec7ec2a913c15ba037ab7744a42b2b2). 

We don't have plans to push a patch at this time. 

I'm going to close this issue - if your issue is something else, or I'm misunderstanding this issue, please either re-open or create a new issue.
